"""Shared components for WP6 dashboards."""

from wp6_data.shared.charts import (
    PRESENCE_NONE_COLOR,
    build_weekly_coverage,
    make_bar_chart,
    make_dual_axis_chart,
    make_line_chart,
    make_schedule_chart,
    make_stacked_area_chart,
    prepare_comparison,
    render_coverage_grid,
)
from wp6_data.shared.cycles import (
    Cohort,
    CohortSpec,
    CycleSpec,
    cohort_for_date,
    exposure,
    generate_cohorts,
    overlap_at,
)
from wp6_data.shared.templates import (
    build_explore_tabs,
    default_date_range,
    pill_row,
    render_card,
    render_dashboard_page,
    render_date_filter,
    render_device_table,
    render_explore_tabs,
    render_hub_card,
    render_hub_grid,
    render_manual_measurement_table,
    render_page,
    render_sensor_type_table,
    render_stat_grid,
    render_stat_tile,
    render_table,
    render_unified_chart_page,
    resolve_date_range,
    utc_day_bounds,
)
from wp6_data.shared.waterfall import Lane, Marker, render_waterfall

__all__ = [
    "build_explore_tabs",
    "build_weekly_coverage",
    "Cohort",
    "cohort_for_date",
    "CohortSpec",
    "CycleSpec",
    "default_date_range",
    "exposure",
    "generate_cohorts",
    "Lane",
    "make_bar_chart",
    "make_dual_axis_chart",
    "make_line_chart",
    "make_schedule_chart",
    "make_stacked_area_chart",
    "Marker",
    "overlap_at",
    "prepare_comparison",
    "PRESENCE_NONE_COLOR",
    "pill_row",
    "render_card",
    "render_coverage_grid",
    "render_dashboard_page",
    "render_date_filter",
    "render_device_table",
    "render_explore_tabs",
    "render_hub_card",
    "render_hub_grid",
    "render_manual_measurement_table",
    "render_page",
    "render_sensor_type_table",
    "render_stat_grid",
    "render_stat_tile",
    "render_table",
    "render_unified_chart_page",
    "render_waterfall",
    "resolve_date_range",
    "utc_day_bounds",
]
