{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
stringData:
  api-token: {{ .Values.secrets.apiToken | quote }}
  neo4j-password: {{ .Values.secrets.neo4jPassword | quote }}
{{- end }}
