"""Blue dashboard dependencies: config, TimescaleDB helpers.

The SPoHF datalake is the single automated source, so reads are unfiltered:
every row in ``readings`` is visible. ``source`` distinguishes manual uploads
from automated ingest, mirroring red.
"""

from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import pandas as pd
from psycopg.rows import dict_row

from wp6_data.config import Settings
from wp6_data.db import close_pool, get_pool, init_pool
from wp6_data.shared.aggregation import CHART_AGG_FUNCS
from wp6_data.shared.export import get_export_metadata as _get_export_metadata
from wp6_data.shared.metadata import MetadataRegistry

metadata = MetadataRegistry(Path(__file__).parent / "metadata.yaml")

# Manual-source values written to readings.`source` (e.g. "insects"). Derived
# from metadata (single source of truth: sensors whose metadata declares a
# `source`). Automated rows keep the 'unknown' default.
MANUAL_SOURCES: tuple[str, ...] = tuple(sorted({
    m.source for m in metadata.sensor_defaults.values() if m.source
}))

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(Settings().blue_export_dir)


async def init_db(dsn: str) -> None:
    """Initialise the connection pool (call on app startup)."""
    from wp6_data.blue.tsdb import ensure_schema_blue

    pool = await init_pool(dsn)
    await ensure_schema_blue(pool)


async def close_db() -> None:
    """Close the connection pool (call on app shutdown)."""
    await close_pool()


async def fetch_data(
    sensor_tags: list[str] | None = None,
    device_names: list[str] | None = None,
    start: datetime | None = None,
    end: datetime | None = None,
    limit: int = 500000,
    *,
    bucket: timedelta | None = None,
    agg: str | None = None,
) -> pd.DataFrame:
    """Fetch sensor readings from TimescaleDB.

    With ``bucket`` + ``agg`` set, aggregation is pushed into a
    ``time_bucket`` GROUP BY so the row ``limit`` caps bucketed rows, not raw
    readings — see :func:`wp6_data.shared.aggregation.bucket_and_aggregate`
    for the contract the fallback backends mirror.
    """
    pool = get_pool()
    params: dict[str, Any] = {}

    conditions: list[str] = []
    if sensor_tags:
        conditions.append("sensor_tag = ANY(%(tags)s)")
        params["tags"] = sensor_tags
    if device_names:
        conditions.append("device_name = ANY(%(devices)s)")
        params["devices"] = device_names
    if start:
        conditions.append("time >= %(start)s")
        params["start"] = start
    if end:
        conditions.append("time <= %(end)s")
        params["end"] = end

    # No source filter remains, so an unconstrained fetch has no conditions at all.
    where = " AND ".join(conditions) if conditions else "TRUE"
    params["limit"] = limit
    columns = ["device", "sensor", "time", "value"]

    if bucket is not None and agg is not None:
        if agg not in CHART_AGG_FUNCS:
            raise ValueError(f"Unknown aggregation {agg!r}")
        params["bucket"] = bucket
        params["tz"] = Settings().display_timezone
        # avg/min/max/sum are valid PG aggregate names — agg is whitelisted.
        # GROUP BY / ORDER BY the real columns + the time_bucket expression,
        # NOT the `AS time` alias: it collides with readings.time, and
        # Postgres resolves that ambiguity differently in GROUP BY (input
        # column) vs ORDER BY (output alias), which silently defeats the
        # bucketing and disorders ties.
        query = f"""
            SELECT device_name AS device, sensor_tag AS sensor,
                   time_bucket(%(bucket)s, time, %(tz)s) AS time,
                   {agg}(value) AS value,
                   min(value) AS value_min,
                   max(value) AS value_max,
                   count(value) AS count
            FROM readings
            WHERE {where}
            GROUP BY device_name, sensor_tag, time_bucket(%(bucket)s, time, %(tz)s)
            ORDER BY time_bucket(%(bucket)s, time, %(tz)s)
            LIMIT %(limit)s
        """
        columns = [
            "device", "sensor", "time", "value",
            "value_min", "value_max", "count",
        ]
    else:
        query = f"""
            SELECT device_name AS device, sensor_tag AS sensor,
                   time, value
            FROM readings
            WHERE {where}
            ORDER BY time
            LIMIT %(limit)s
        """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        records = await cur.fetchall()

    if not records:
        return pd.DataFrame(columns=columns)
    df = pd.DataFrame(records)
    if not df.empty:
        df["time"] = pd.to_datetime(df["time"], utc=True)
        for col in ("value", "value_min", "value_max"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        df = df.sort_values("time")
    return df


async def _fetch_sensors_from_cagg() -> list[dict[str, Any]]:
    """Sensor list + counts: automated rows from the cagg, manual rows direct.

    Manual rows land in the cagg too, but the cagg's per-day counts are summed
    while the manual query counts raw rows, so manual ``(device, sensor)`` pairs
    are read straight from ``readings`` and override the cagg row.
    """
    pool = get_pool()
    params: dict[str, Any] = {}

    cagg_query = """
        SELECT device_name AS device, sensor_tag AS sensor,
               sum(reading_count)  AS readings,
               min(first_reading)  AS earliest,
               max(last_reading)   AS latest
        FROM sensors_daily_summary
        GROUP BY device_name, sensor_tag
        ORDER BY readings DESC
    """
    manual_query = """
        SELECT device_name AS device, sensor_tag AS sensor,
               count(*)  AS readings,
               min(time) AS earliest,
               max(time) AS latest
        FROM readings
        WHERE source = ANY(%(manual_sources)s)
        GROUP BY device_name, sensor_tag
        ORDER BY readings DESC
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(cagg_query, params)
        cagg_rows = await cur.fetchall()
        if not MANUAL_SOURCES:
            return cagg_rows
        await cur.execute(
            manual_query, {"manual_sources": list(MANUAL_SOURCES)},
        )
        manual_rows = await cur.fetchall()

    manual_keys = {(r["device"], r["sensor"]) for r in manual_rows}
    automated = [
        r for r in cagg_rows
        if (r["device"], r["sensor"]) not in manual_keys
    ]
    return automated + manual_rows


async def fetch_available_sensors() -> list[dict[str, Any]]:
    """Get list of sensors with reading counts and date range (cached, via cagg)."""
    from wp6_data.shared.sensor_summary import get_sensor_summary

    return await get_sensor_summary("blue", _fetch_sensors_from_cagg)


async def fetch_daily_coverage() -> list[dict[str, Any]]:
    """Distinct days with data per device+sensor, tagged manual vs automated.

    Read straight from the ``sensors_daily_summary`` cagg, which is derived from
    ``readings`` and carries the ``source`` categorical. A day where every row of
    a (device, sensor) is a manual slug is flagged ``manual=True``. Because the
    cagg refreshes from readings, a day whose readings were deleted stops
    reporting — unlike the old insert-only ``daily_coverage`` table it replaces.
    The trade-off is a freshness lag: the current day can trail by one refresh
    cycle (~15 min), acceptable for a status view.
    """
    pool = get_pool()
    params: dict[str, Any] = {"manual_sources": list(MANUAL_SOURCES)}

    query = """
        SELECT device_name AS device, sensor_tag AS sensor, bucket::date AS day,
               bool_or(source = ANY(%(manual_sources)s)) AS manual
        FROM sensors_daily_summary
        GROUP BY device_name, sensor_tag, bucket::date
        ORDER BY sensor_tag, device_name, day
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        return await cur.fetchall()


async def fetch_sync_metrics() -> list[dict[str, Any]]:
    """Fetch sync metadata for every endpoint (only the datalake sync remains)."""
    pool = get_pool()

    query = """
        SELECT endpoint,
               last_run_at,
               last_run_success,
               last_run_duration_sec AS duration_seconds,
               last_run_records AS records,
               last_error AS error,
               last_api_status AS api_status,
               last_api_error_detail AS api_error_detail,
               total_runs,
               total_failures,
               last_timestamp AS last_data_timestamp
        FROM sync_metadata
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query)
        return await cur.fetchall()


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    return _get_export_metadata(EXPORT_DIR)
