"""Blue dashboard dependencies: config, TimescaleDB helpers.

All query functions accept an optional ``project`` parameter:
- ``None`` (default) → exclude "yookr-direct" (SPoHF Datalake view)
- A string → include only that project (used by the Yookr view)
"""

from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd
from psycopg.rows import dict_row

from wp6_data.config import Settings
from wp6_data.db import close_pool, get_pool, init_pool
from wp6_data.shared.export import get_export_metadata as _get_export_metadata

# Serve static files (logo, etc.) from project root
# __file__ is src/wp6_data/blue/deps.py, so .parent x4 gets to wp6-data/
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent

YOOKR_PROJECT = "yookr-direct"

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(Settings().blue_export_dir)


async def init_db(dsn: str) -> None:
    """Initialise the connection pool (call on app startup)."""
    from wp6_data.db.schema import ensure_schema

    pool = await init_pool(dsn)
    await ensure_schema(pool)


async def close_db() -> None:
    """Close the connection pool (call on app shutdown)."""
    await close_pool()


def _project_filter(project: str | None) -> tuple[str, dict[str, Any]]:
    """Build a SQL WHERE fragment for project filtering.

    Returns (sql_fragment, params_dict).
    - project=None  → exclude yookr-direct
    - project=<str> → include only that project
    """
    if project is not None:
        return "project = %(project)s", {"project": project}
    return "project != %(excluded_project)s", {"excluded_project": YOOKR_PROJECT}


async def fetch_data(
    sensor_tags: list[str] | None = None,
    device_names: list[str] | None = None,
    start: datetime | None = None,
    end: datetime | None = None,
    limit: int = 500000,
    project: str | None = None,
) -> pd.DataFrame:
    """Fetch sensor readings from TimescaleDB."""
    pool = get_pool()
    proj_clause, params = _project_filter(project)

    conditions = [proj_clause]
    if sensor_tags:
        conditions.append("sensor_tag = ANY(%(tags)s)")
        params["tags"] = sensor_tags
    if device_names:
        conditions.append("device_name = ANY(%(devices)s)")
        params["devices"] = device_names
    if start:
        conditions.append("time >= %(start)s")
        params["start"] = start
    if end:
        conditions.append("time <= %(end)s")
        params["end"] = end

    where = " AND ".join(conditions)
    params["limit"] = limit

    query = f"""
        SELECT device_name AS device, sensor_tag AS sensor,
               time, value
        FROM readings
        WHERE {where}
        ORDER BY time
        LIMIT %(limit)s
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        records = await cur.fetchall()

    if not records:
        return pd.DataFrame(columns=["device", "sensor", "time", "value"])
    df = pd.DataFrame(records)
    if not df.empty:
        df["time"] = pd.to_datetime(df["time"], utc=True)
        df["value"] = pd.to_numeric(df["value"], errors="coerce")
        df = df.sort_values("time")
    return df


async def _fetch_sensors_from_cagg(project: str | None = None) -> list[dict[str, Any]]:
    """Query the sensors_daily_summary continuous aggregate."""
    pool = get_pool()
    proj_clause, params = _project_filter(project)

    query = f"""
        SELECT device_name AS device, sensor_tag AS sensor,
               sum(reading_count)  AS readings,
               min(first_reading)  AS earliest,
               max(last_reading)   AS latest
        FROM sensors_daily_summary
        WHERE {proj_clause}
        GROUP BY device_name, sensor_tag
        ORDER BY readings DESC
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        return await cur.fetchall()


async def fetch_available_sensors(project: str | None = None) -> list[dict[str, Any]]:
    """Get list of sensors with reading counts and date range (cached, via cagg)."""
    from wp6_data.shared.sensor_summary import get_sensor_summary

    cache_key = f"blue:{project or 'default'}"
    return await get_sensor_summary(cache_key, _fetch_sensors_from_cagg, project=project)


async def fetch_daily_coverage(project: str | None = None) -> list[dict[str, Any]]:
    """Get distinct days with data per device+sensor from daily_coverage table."""
    pool = get_pool()
    proj_clause, params = _project_filter(project)

    query = f"""
        SELECT dc.device_name AS device, dc.sensor_tag AS sensor, dc.day
        FROM daily_coverage dc
        WHERE EXISTS (
            SELECT 1 FROM readings r
            WHERE r.device_name = dc.device_name
              AND r.sensor_tag = dc.sensor_tag
              AND {proj_clause}
            LIMIT 1
        )
        ORDER BY dc.sensor_tag, dc.device_name, dc.day
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        return await cur.fetchall()


async def fetch_sync_metrics(project: str | None = None) -> list[dict[str, Any]]:
    """Fetch sync metadata, filtered by data-source view.

    - project=None  → exclude yookr-direct endpoint (SPoHF Datalake view)
    - project=<str> → include only that endpoint
    """
    pool = get_pool()

    if project is not None:
        where = "WHERE endpoint = %(endpoint)s"
        params: dict[str, Any] = {"endpoint": project}
    else:
        where = "WHERE endpoint != %(excluded)s"
        params = {"excluded": YOOKR_PROJECT}

    query = f"""
        SELECT endpoint,
               last_run_at,
               last_run_success,
               last_run_duration_sec AS duration_seconds,
               last_run_records AS records,
               last_error AS error,
               last_api_status AS api_status,
               last_api_error_detail AS api_error_detail,
               total_runs,
               total_failures,
               last_timestamp AS last_data_timestamp
        FROM sync_metadata
        {where}
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        return await cur.fetchall()


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    return _get_export_metadata(EXPORT_DIR)
