"""Blue dashboard dependencies: config, TimescaleDB helpers.

All query functions accept an optional ``project`` parameter:
- ``None`` (default) → exclude "yookr-direct" (SPoHF Datalake view)
- A string → include only that project (used by the Yookr view)
"""

from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import pandas as pd
from psycopg.rows import dict_row

from wp6_data.config import Settings
from wp6_data.db import close_pool, get_pool, init_pool
from wp6_data.shared.aggregation import CHART_AGG_FUNCS
from wp6_data.shared.export import get_export_metadata as _get_export_metadata
from wp6_data.shared.metadata import MetadataRegistry

YOOKR_PROJECT = "yookr-direct"

metadata = MetadataRegistry(Path(__file__).parent / "metadata.yaml")

# Manual-source values written to readings.`source` (e.g. "insects").
# Manual data is farm-level — not an automated pipeline — so it stays visible
# regardless of the yookr-vs-datalake `project` toggle. Derived from metadata
# (single source of truth: sensors whose metadata declares a `source`).
MANUAL_SOURCES: tuple[str, ...] = tuple(sorted({
    m.source for m in metadata.sensor_defaults.values() if m.source
}))

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(Settings().blue_export_dir)


async def init_db(dsn: str) -> None:
    """Initialise the connection pool (call on app startup)."""
    from wp6_data.blue.tsdb import ensure_schema_blue

    pool = await init_pool(dsn)
    await ensure_schema_blue(pool)


async def close_db() -> None:
    """Close the connection pool (call on app shutdown)."""
    await close_pool()


def _project_filter(project: str | None) -> tuple[str, dict[str, Any]]:
    """WHERE fragment for the automated-source (``project``) view only.

    - project=None  → exclude yookr-direct (the SPoHF Datalake view)
    - project=<str> → only that project (the Yookr view)
    """
    if project is not None:
        return "project = %(project)s", {"project": project}
    return "project != %(excluded_project)s", {"excluded_project": YOOKR_PROJECT}


def _visible_filter(project: str | None) -> tuple[str, dict[str, Any]]:
    """Rows visible under a data-source view.

    Automated rows are filtered by ``project`` (the toggle); manually-
    uploaded rows carry a non-default ``source`` and are farm-level, so they
    are always included — insect data shows under either view.
    """
    proj_clause, params = _project_filter(project)
    if MANUAL_SOURCES:
        params["manual_sources"] = list(MANUAL_SOURCES)
        return (
            f"({proj_clause} OR source = ANY(%(manual_sources)s))",
            params,
        )
    return proj_clause, params


async def fetch_data(
    sensor_tags: list[str] | None = None,
    device_names: list[str] | None = None,
    start: datetime | None = None,
    end: datetime | None = None,
    limit: int = 500000,
    project: str | None = None,
    *,
    bucket: timedelta | None = None,
    agg: str | None = None,
) -> pd.DataFrame:
    """Fetch sensor readings from TimescaleDB.

    With ``bucket`` + ``agg`` set, aggregation is pushed into a
    ``time_bucket`` GROUP BY so the row ``limit`` caps bucketed rows, not raw
    readings — see :func:`wp6_data.shared.aggregation.bucket_and_aggregate`
    for the contract the fallback backends mirror.
    """
    pool = get_pool()
    proj_clause, params = _visible_filter(project)

    conditions = [proj_clause]
    if sensor_tags:
        conditions.append("sensor_tag = ANY(%(tags)s)")
        params["tags"] = sensor_tags
    if device_names:
        conditions.append("device_name = ANY(%(devices)s)")
        params["devices"] = device_names
    if start:
        conditions.append("time >= %(start)s")
        params["start"] = start
    if end:
        conditions.append("time <= %(end)s")
        params["end"] = end

    where = " AND ".join(conditions)
    params["limit"] = limit
    columns = ["device", "sensor", "time", "value"]

    if bucket is not None and agg is not None:
        if agg not in CHART_AGG_FUNCS:
            raise ValueError(f"Unknown aggregation {agg!r}")
        params["bucket"] = bucket
        params["tz"] = Settings().display_timezone
        # avg/min/max/sum are valid PG aggregate names — agg is whitelisted.
        # GROUP BY / ORDER BY the real columns + the time_bucket expression,
        # NOT the `AS time` alias: it collides with readings.time, and
        # Postgres resolves that ambiguity differently in GROUP BY (input
        # column) vs ORDER BY (output alias), which silently defeats the
        # bucketing and disorders ties.
        query = f"""
            SELECT device_name AS device, sensor_tag AS sensor,
                   time_bucket(%(bucket)s, time, %(tz)s) AS time,
                   {agg}(value) AS value,
                   min(value) AS value_min,
                   max(value) AS value_max,
                   count(value) AS count
            FROM readings
            WHERE {where}
            GROUP BY device_name, sensor_tag, time_bucket(%(bucket)s, time, %(tz)s)
            ORDER BY time_bucket(%(bucket)s, time, %(tz)s)
            LIMIT %(limit)s
        """
        columns = [
            "device", "sensor", "time", "value",
            "value_min", "value_max", "count",
        ]
    else:
        query = f"""
            SELECT device_name AS device, sensor_tag AS sensor,
                   time, value
            FROM readings
            WHERE {where}
            ORDER BY time
            LIMIT %(limit)s
        """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        records = await cur.fetchall()

    if not records:
        return pd.DataFrame(columns=columns)
    df = pd.DataFrame(records)
    if not df.empty:
        df["time"] = pd.to_datetime(df["time"], utc=True)
        for col in ("value", "value_min", "value_max"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        df = df.sort_values("time")
    return df


async def _fetch_sensors_from_cagg(project: str | None = None) -> list[dict[str, Any]]:
    """Sensor list + counts: automated rows from the cagg, manual rows direct.

    The continuous aggregate groups by ``project`` only (it has no ``source``
    column — adding one would mean recreating the cagg, a heavier migration).
    So automated sensors come from the cagg filtered by the toggle, and
    manually-uploaded sensors are read straight from ``readings`` and merged
    in unconditionally — making manual data visible under either view without
    touching the cagg. Manual ``(device, sensor)`` pairs override any cagg
    row (manual rows land in the cagg under the default ``project`` too).
    """
    pool = get_pool()
    proj_clause, params = _project_filter(project)

    cagg_query = f"""
        SELECT device_name AS device, sensor_tag AS sensor,
               sum(reading_count)  AS readings,
               min(first_reading)  AS earliest,
               max(last_reading)   AS latest
        FROM sensors_daily_summary
        WHERE {proj_clause}
        GROUP BY device_name, sensor_tag
        ORDER BY readings DESC
    """
    manual_query = """
        SELECT device_name AS device, sensor_tag AS sensor,
               count(*)  AS readings,
               min(time) AS earliest,
               max(time) AS latest
        FROM readings
        WHERE source = ANY(%(manual_sources)s)
        GROUP BY device_name, sensor_tag
        ORDER BY readings DESC
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(cagg_query, params)
        cagg_rows = await cur.fetchall()
        if not MANUAL_SOURCES:
            return cagg_rows
        await cur.execute(
            manual_query, {"manual_sources": list(MANUAL_SOURCES)},
        )
        manual_rows = await cur.fetchall()

    manual_keys = {(r["device"], r["sensor"]) for r in manual_rows}
    automated = [
        r for r in cagg_rows
        if (r["device"], r["sensor"]) not in manual_keys
    ]
    return automated + manual_rows


async def fetch_available_sensors(project: str | None = None) -> list[dict[str, Any]]:
    """Get list of sensors with reading counts and date range (cached, via cagg)."""
    from wp6_data.shared.sensor_summary import get_sensor_summary

    cache_key = f"blue:{project or 'default'}"
    return await get_sensor_summary(cache_key, _fetch_sensors_from_cagg, project=project)


async def fetch_daily_coverage(project: str | None = None) -> list[dict[str, Any]]:
    """Distinct days with data per device+sensor, tagged manual vs automated.

    Manual coverage (``source`` is a manual slug) is always visible and flagged
    ``manual=True`` straight from the ``daily_coverage.source`` column — no
    ``readings`` access.

    Automated coverage is matched against the ``sensors_daily_summary`` cagg at
    **day granularity** — ``(device, sensor, day)``, not just ``(device,
    sensor)``. ``daily_coverage`` has no ``project`` column, so a pair-level
    match would show a day under a source-view whenever the *pair* appeared
    anywhere in that view — leaking the other source's days (e.g.
    ``weatherstation:airTemperature`` looked fresh under the Datalake view
    because ``yookr-direct`` wrote those days). The cagg *does* group by
    ``project``, so joining on the day (``bucket::date``, UTC — consistent with
    how ``daily_coverage.day`` derives from ``readings.time``) keeps only the
    days the active source actually owns. The cagg can lag a freshly-ingested
    day by one refresh cycle (~15 min), acceptable for a status view.
    """
    pool = get_pool()
    proj_clause, params = _project_filter(project)
    params["manual_sources"] = list(MANUAL_SOURCES)

    query = f"""
        WITH visible_auto AS (
            SELECT DISTINCT device_name, sensor_tag, bucket::date AS day
            FROM sensors_daily_summary
            WHERE {proj_clause}
        )
        SELECT dc.device_name AS device, dc.sensor_tag AS sensor, dc.day,
               (dc.source = ANY(%(manual_sources)s)) AS manual
        FROM daily_coverage dc
        WHERE dc.source = ANY(%(manual_sources)s)
           OR (dc.device_name, dc.sensor_tag, dc.day)
               IN (SELECT device_name, sensor_tag, day FROM visible_auto)
        ORDER BY dc.sensor_tag, dc.device_name, dc.day
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        return await cur.fetchall()


async def fetch_sync_metrics(project: str | None = None) -> list[dict[str, Any]]:
    """Fetch sync metadata, filtered by data-source view.

    - project=None  → exclude yookr-direct endpoint (SPoHF Datalake view)
    - project=<str> → include only that endpoint
    """
    pool = get_pool()

    if project is not None:
        where = "WHERE endpoint = %(endpoint)s"
        params: dict[str, Any] = {"endpoint": project}
    else:
        where = "WHERE endpoint != %(excluded)s"
        params = {"excluded": YOOKR_PROJECT}

    query = f"""
        SELECT endpoint,
               last_run_at,
               last_run_success,
               last_run_duration_sec AS duration_seconds,
               last_run_records AS records,
               last_error AS error,
               last_api_status AS api_status,
               last_api_error_detail AS api_error_detail,
               total_runs,
               total_failures,
               last_timestamp AS last_data_timestamp
        FROM sync_metadata
        {where}
    """

    async with pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
        await cur.execute(query, params)
        return await cur.fetchall()


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    return _get_export_metadata(EXPORT_DIR)
