"""Configuration via environment variables."""

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from WP6_* environment variables."""

    model_config = SettingsConfigDict(
        env_prefix="WP6_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # SPoHF API
    api_base_url: str = "https://backoffice.spohf.com"
    api_token: str = ""  # SPoHF API bearer token (required for datalake sync)

    # TimescaleDB
    tsdb_url: str = "postgresql://wp6:wp6dev@localhost:5433/wp6_blue"

    # Sync behavior
    sync_page_size: int = 1000
    sync_mode: str = "incremental"  # "full" or "incremental"
    sync_window_days: int = 1  # Days per window

    # Endpoints to sync (comma-separated)
    endpoints: str = "yookr-data"

    # Yookr API (direct sensor queries)
    yookr_base_url: str = "https://api.yookr.org"
    yookr_email: str = ""
    yookr_password: str = ""

    # Chart query limit (max data points per series in /api/series)
    chart_query_limit: int = 100000

    # Blue dashboard data source
    blue_default_source: str = "spohf-datalake"  # "spohf-datalake" or "yookr"

    # Blue CSV export directory (pre-generated by nightly job)
    blue_export_dir: str = "/data/exports"

    # Optional CSV path for farm-wide fertigation events overlay in /chart.
    # If empty, blue routes use the newest manual upload under
    # {blue_upload_dir}/fertigation_events/*.csv, then fall back to a
    # workspace-relative dev path uploads-blue/fertigation/fertigation_events.csv.
    blue_fertigation_events_csv: str = ""

    # PVC mount for blue manual uploads (insect CSV, future sources). Mirrors
    # red's upload_dir: files land at {blue_upload_dir}/{slug}/{sha256}{suffix};
    # only the latest 2 per source are kept on disk (audit rows kept forever).
    blue_upload_dir: str = "/data/blue-manual-uploads"

    # Display
    display_timezone: str = "Europe/Amsterdam"

    # Logging
    log_level: str = "INFO"
    log_format: str = "json"  # "json" or "console"

    @property
    def endpoint_list(self) -> list[str]:
        """Parse endpoints string into list."""
        return [e.strip() for e in self.endpoints.split(",") if e.strip()]


class OIDCSettings(BaseSettings):
    """OIDC settings shared by both dashboards, loaded from WP6_OIDC_* environment variables."""

    model_config = SettingsConfigDict(
        env_prefix="WP6_OIDC_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    issuer: str = "https://auth.fontysvenlo.dev/realms/spohf"
    client_id: str = "wp6-data"
    client_secret: str = ""  # Required at startup - set via WP6_OIDC_CLIENT_SECRET
    session_secret: str = ""  # Required at startup - set via WP6_OIDC_SESSION_SECRET
    redirect_base: str = ""  # Public base URL of the app, e.g. https://wp6-red.example.com
    dev_auth: bool = False  # Skip OIDC entirely and inject a fake user (development only)


class RedSettings(BaseSettings):
    """WP6 Red dashboard settings loaded from WP6_RED_* environment variables."""

    model_config = SettingsConfigDict(
        env_prefix="WP6_RED_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    db_host: str = "localhost"
    db_port: int = 3306
    db_name: str = "spohf2"
    db_user: str = "root"
    db_password: str = ""

    # TimescaleDB connection for manually-uploaded measurements (Sijia, etc.)
    tsdb_url: str

    export_dir: str = "/data/exports"

    # PVC mount for manual uploads (issue 008). Files land at
    # {upload_dir}/{source}/{sha256}.xlsx; only the latest 2 per source kept.
    upload_dir: str = "/data/manual-uploads"
