"""WP6 Red Dashboard - MySQL-backed sensor visualization with authentication."""

import json
import os
import secrets
from contextlib import asynccontextmanager
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Annotated

import pandas as pd
from dotenv import load_dotenv
from fastapi import Depends, FastAPI, HTTPException, Query
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from fastapi.staticfiles import StaticFiles

from wp6_data.red.db import MEASUREMENT_GROUPS, MEASUREMENTS_TO_TABLES, MySQLConnection
from wp6_data.red.dli import (
    DEFAULT_TRAINING_START,
    NATURAL_LIGHT_SENSOR,
    SECONDS_PER_HOUR,
    TOTAL_LIGHT_SENSOR,
    UMOL_TO_MOL,
    OpenMeteoClient,
    align_outdoor_to_indoor_daily,
    align_weather_outdoor_hourly,
    analyze_reporting_frequency,
    calculate_correlation_comparison,
    calculate_daily_dli,
    calculate_dli_trendline,
    calculate_hourly_par,
    calculate_lamp_contribution,
    derive_daily_lamp_profile,
    estimate_hourly_natural_par,
    estimate_remaining_dli,
    get_model,
    infer_lamp_schedule_hourly,
    subtract_lamp_from_sensor,
)
from wp6_data.shared import (
    make_dual_axis_chart,
    make_line_chart,
    make_schedule_chart,
    prepare_comparison,
    render_compare_form,
    render_date_filter,
    render_page,
    resolve_date_range,
)

load_dotenv()

# MySQL connection settings
DB_HOST = os.getenv("WP6_RED_DB_HOST", "localhost")
DB_PORT = int(os.getenv("WP6_RED_DB_PORT", "3306"))
DB_NAME = os.getenv("WP6_RED_DB_NAME", "spohf2")
DB_USER = os.getenv("WP6_RED_DB_USER", "root")
DB_PASSWORD = os.getenv("WP6_RED_DB_PASSWORD", "")

# Auth users: "user1:pass1,user2:pass2" (required, no default)
AUTH_USERS_STR = os.getenv("WP6_RED_AUTH_USERS", "")

# Admin users: comma-separated list of usernames with admin access
ADMIN_USERS_STR = os.getenv("WP6_RED_ADMIN_USERS", "admin")
ADMIN_USERS = {u.strip() for u in ADMIN_USERS_STR.split(",") if u.strip()}


def parse_users(users_str: str) -> dict[str, str]:
    """Parse users from comma-separated string."""
    if not users_str:
        return {}
    users = {}
    for pair in users_str.split(","):
        if ":" in pair:
            username, password = pair.split(":", 1)
            users[username.strip()] = password.strip()
    return users


AUTH_USERS = parse_users(AUTH_USERS_STR)

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(os.getenv("WP6_RED_EXPORT_DIR", "/data/exports"))

# Database connection (managed via lifespan)
db: MySQLConnection | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage database connection lifecycle."""
    global db
    db = MySQLConnection(
        host=DB_HOST,
        port=DB_PORT,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME,
    )
    await db.connect()
    yield
    await db.close()


app = FastAPI(title="WP6 Red - Sensor Dashboard", lifespan=lifespan)
security = HTTPBasic()

# Serve static files
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
if (PROJECT_ROOT / "static").exists():
    app.mount("/static", StaticFiles(directory=PROJECT_ROOT / "static"), name="static")


def verify_auth(credentials: Annotated[HTTPBasicCredentials, Depends(security)]) -> str:
    """Verify Basic Auth credentials."""
    if not AUTH_USERS:
        raise HTTPException(
            status_code=500,
            detail="No users configured. Set WP6_RED_AUTH_USERS env var.",
        )

    if credentials.username not in AUTH_USERS:
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Basic"},
        )

    expected_password = AUTH_USERS[credentials.username]
    if not secrets.compare_digest(credentials.password.encode(), expected_password.encode()):
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Basic"},
        )

    return credentials.username


def is_admin(user: str) -> bool:
    """Check if user has admin access."""
    return user in ADMIN_USERS


def verify_admin_auth(user: str = Depends(verify_auth)) -> str:
    """Verify user has admin access (for model training etc.)."""
    if not is_admin(user):
        raise HTTPException(
            status_code=403,
            detail="Admin access required",
        )
    return user


def _export_info_html(export_meta: dict | None) -> str:
    """Generate HTML snippet showing export metadata."""
    if not export_meta:
        return "<small>CSV exports not yet available.</small>"
    return ""


@app.get("/health")
async def health() -> dict[str, str]:
    """Health check endpoint for k8s probes (no auth required)."""
    return {"status": "ok"}


@app.get("/", response_class=HTMLResponse)
async def home(user: str = Depends(verify_auth)) -> str:
    """Dashboard home page - list available sensors."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>")

    sensors = await db.get_available_sensors()
    export_meta = get_export_metadata()
    available_exports = export_meta.get("tables", {}) if export_meta else {}

    # Build sensor list HTML
    sensor_rows = []
    for s in sensors:
        table = s["table"]
        devices = s["devices"]
        readings = s["readings"]
        measurements = ", ".join(s["measurements"])
        if table in available_exports:
            export_ts = available_exports[table][:16].replace("T", " ")  # Date + time
            download_link = (
                f'<a href="/download/{table}" title="Download CSV">CSV</a> '
                f"<small>({export_ts})</small>"
            )
        else:
            download_link = "-"
        sensor_rows.append(
            f'<tr>'
            f'<td><a href="/table/{table}">{table}</a></td>'
            f'<td>{devices}</td>'
            f'<td>{readings:,}</td>'
            f'<td>{measurements}</td>'
            f'<td>{download_link}</td>'
            f'</tr>'
        )

    table_html = f"""
        <table>
            <thead>
                <tr>
                    <th>Sensor Type</th>
                    <th>Devices</th>
                    <th>Readings</th>
                    <th>Measurements</th>
                    <th>Download</th>
                </tr>
            </thead>
            <tbody>
                {''.join(sensor_rows)}
            </tbody>
        </table>
    """

    # Build measurement types section (hide items that are part of a group)
    grouped_measurements = set()
    for group_cols in MEASUREMENT_GROUPS.values():
        grouped_measurements.update(group_cols)

    measurement_rows = []
    for measurement, tables in sorted(MEASUREMENTS_TO_TABLES.items()):
        if measurement in grouped_measurements:
            continue  # Skip individual items that are shown as a group
        measurement_rows.append(
            f'<tr>'
            f'<td><a href="/measurement/{measurement}">{measurement}</a></td>'
            f'<td>{", ".join(sorted(tables))}</td>'
            f'</tr>'
        )

    measurement_html = f"""
        <table>
            <thead>
                <tr>
                    <th>Measurement</th>
                    <th>Available in Sensors</th>
                </tr>
            </thead>
            <tbody>
                {''.join(measurement_rows)}
            </tbody>
        </table>
    """

    extra_css = """
        .user-info { float: right; color: #666; font-size: 0.9em; }
    """

    content = f"""
        <div class="user-info">Logged in as: {user}</div>
        <h1>WP6 Red - Sensor Dashboard</h1>

        <article>
            <h2>Light Analysis (DLI)</h2>
            <p>Daily Light Integral analysis and optimization tools.</p>
            <a href="/dli" role="button">DLI Dashboard</a>
        </article>

        <article>
            <h2>Custom Compare</h2>
            <p>Create a custom dual-axis chart
            by selecting two sensor/measurement combinations.</p>
            <a href="/compare" role="button">Compare</a>
        </article>

        <article>
            <h2>Compare by Measurement Type</h2>
            <p>View all sensors measuring the same thing:</p>
            {measurement_html}
        </article>

        <article>
            <h2>Browse by Sensor Type</h2>
            {table_html}
            {_export_info_html(export_meta)}
        </article>
    """

    return render_page("WP6 Red - Sensor Dashboard", content, extra_css=extra_css)


@app.get("/measurement/{measurement}", response_class=HTMLResponse)
async def measurement_view(
    measurement: str,
    user: str = Depends(verify_auth),
    limit: int = Query(100000, description="Max records per sensor table"),
    start: Annotated[date | None, Query(description="Start date (default: 7 days ago)")] = None,
    end: Annotated[date | None, Query(description="End date (default: today)")] = None,
) -> str:
    """Chart a measurement type across all sensors that have it."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    if measurement not in MEASUREMENTS_TO_TABLES:
        return render_page(
            f"{measurement} - WP6 Red",
            f"<h1>Unknown measurement: {measurement}</h1>",
            show_back_link=True,
        )

    start, end, start_dt, end_dt = resolve_date_range(start, end)

    try:
        df = await db.get_readings_by_measurement(
            measurement, start=start_dt, end=end_dt, limit_per_table=limit,
        )
    except Exception as e:
        return render_page(
            f"{measurement} - WP6 Red",
            f"<h1>Error: {e}</h1>",
            show_back_link=True,
        )

    filter_html = render_date_filter(start, end)

    if df.empty:
        return render_page(
            f"{measurement} - WP6 Red",
            filter_html + "<h1>No data found</h1>",
            show_back_link=True,
        )

    tables = MEASUREMENTS_TO_TABLES[measurement]
    fig = make_line_chart(df, title=f"{measurement} - All Sensors ({', '.join(tables)})")
    chart_html = fig.to_html(full_html=False, include_plotlyjs="cdn")

    stats_html = f"<small>{len(df):,} data points</small>"

    return render_page(
        f"{measurement} - WP6 Red",
        filter_html + stats_html + chart_html,
        show_logo=False,
        show_footer=False,
        show_back_link=True,
    )


@app.get("/table/{table}", response_class=HTMLResponse)
async def table_view(table: str, user: str = Depends(verify_auth)) -> str:
    """Show devices for a sensor table."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    try:
        devices = await db.get_devices_for_table(table)
    except ValueError as e:
        return render_page(
            f"{table} - WP6 Red",
            f"<h1>Error: {e}</h1>",
            show_back_link=True,
        )

    device_list = "".join(
        f'<li><a href="/chart/{table}/{device}">{device}</a></li>' for device in devices
    )

    content = f"""
        <h1>{table}</h1>
        <h2>Devices</h2>
        <ul>{device_list}</ul>
        <h2>View All Devices</h2>
        <p><a href="/chart/{table}">Combined chart (all devices)</a></p>
    """

    return render_page(f"{table} - WP6 Red", content, show_back_link=True)


@app.get("/chart/{table}", response_class=HTMLResponse)
async def chart_all(
    table: str,
    user: str = Depends(verify_auth),
    limit: int = Query(50000, description="Max records to fetch"),
    start: Annotated[date | None, Query(description="Start date (default: 7 days ago)")] = None,
    end: Annotated[date | None, Query(description="End date (default: today)")] = None,
) -> str:
    """Chart all devices for a sensor table."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    start, end, start_dt, end_dt = resolve_date_range(start, end)

    try:
        df = await db.get_readings(table, start=start_dt, end=end_dt, limit=limit)
    except ValueError as e:
        return render_page(
            f"{table} - WP6 Red",
            f"<h1>Error: {e}</h1>",
            show_back_link=True,
            back_url=f"/table/{table}",
        )

    filter_html = render_date_filter(start, end)

    if df.empty:
        return render_page(
            f"{table} - WP6 Red",
            filter_html + "<h1>No data found</h1>",
            show_back_link=True,
            back_url=f"/table/{table}",
        )

    fig = make_line_chart(df, title=f"{table} - All Devices")
    chart_html = fig.to_html(full_html=False, include_plotlyjs="cdn")

    stats_html = f"<small>{len(df):,} data points</small>"

    return render_page(
        f"{table} - WP6 Red",
        filter_html + stats_html + chart_html,
        show_logo=False,
        show_footer=False,
        show_back_link=True,
        back_url=f"/table/{table}",
    )


@app.get("/chart/{table}/{device_id}", response_class=HTMLResponse)
async def chart_device(
    table: str,
    device_id: str,
    user: str = Depends(verify_auth),
    limit: int = Query(50000, description="Max records to fetch"),
    start: Annotated[date | None, Query(description="Start date (default: 7 days ago)")] = None,
    end: Annotated[date | None, Query(description="End date (default: today)")] = None,
) -> str:
    """Chart a specific device."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    start, end, start_dt, end_dt = resolve_date_range(start, end)

    try:
        df = await db.get_readings(
            table, device_id=device_id, start=start_dt, end=end_dt, limit=limit,
        )
    except ValueError as e:
        return render_page(
            f"{device_id} - WP6 Red",
            f"<h1>Error: {e}</h1>",
            show_back_link=True,
            back_url=f"/table/{table}",
        )

    filter_html = render_date_filter(start, end)

    if df.empty:
        return render_page(
            f"{device_id} - WP6 Red",
            filter_html + "<h1>No data found</h1>",
            show_back_link=True,
            back_url=f"/table/{table}",
        )

    # Check if we can do dual axis (2 different measurements)
    sensors = df["sensor"].unique()
    if len(sensors) == 2:
        fig = make_dual_axis_chart(df, sensors[0], sensors[1], title=f"{table} - {device_id}")
    else:
        fig = make_line_chart(df, title=f"{table} - {device_id}")

    chart_html = fig.to_html(full_html=False, include_plotlyjs="cdn")

    stats_html = f"<small>{len(df):,} data points</small>"

    return render_page(
        f"{device_id} - WP6 Red",
        filter_html + stats_html + chart_html,
        show_logo=False,
        show_footer=False,
        show_back_link=True,
        back_url=f"/table/{table}",
    )


@app.get("/compare", response_class=HTMLResponse)
async def compare_form(user: str = Depends(verify_auth)) -> str:
    """Form to select two device/measurement pairs for a custom dual-axis chart."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    devices = await db.get_all_devices()
    device_data = {did: info["measurements"] for did, info in devices.items()}

    form_html = render_compare_form(device_data, action_url="/compare/chart")
    content = f"""
        <h1>Custom Compare</h1>
        <p>Select two device/measurement combinations to plot on a dual y-axis chart.</p>
        {form_html}
    """

    return render_page("Custom Compare - WP6 Red", content, show_back_link=True)


@app.get("/compare/chart", response_class=HTMLResponse)
async def compare_chart(
    left_device: str = Query(...),
    left_measurement: str = Query(...),
    right_device: str = Query(""),
    right_measurement: str = Query(""),
    user: str = Depends(verify_auth),
    start: Annotated[date | None, Query()] = None,
    end: Annotated[date | None, Query()] = None,
) -> str:
    """Render a dual-axis chart for two user-selected device/measurement pairs."""
    if not db:
        return render_page("WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    has_right = bool(right_device and right_measurement)

    start, end, start_dt, end_dt = resolve_date_range(start, end)

    try:
        left_df = await db.get_readings_for_comparison(
            left_device, left_measurement, start=start_dt, end=end_dt,
        )
        right_df = (
            await db.get_readings_for_comparison(
                right_device, right_measurement, start=start_dt, end=end_dt,
            )
            if has_right
            else pd.DataFrame(columns=["device", "sensor", "time", "value"])
        )
    except ValueError as e:
        return render_page(
            "Compare - WP6 Red", f"<h1>Error: {e}</h1>",
            show_back_link=True, back_url="/compare",
        )

    left_label = f"{left_device} | {left_measurement}"
    right_label = f"{right_device} | {right_measurement}" if has_right else ""
    df, left_label, right_label = prepare_comparison(
        left_df, right_df, left_label, right_label,
    )

    extra_params: dict[str, str] = {
        "left_device": left_device,
        "left_measurement": left_measurement,
    }
    if has_right:
        extra_params["right_device"] = right_device
        extra_params["right_measurement"] = right_measurement
    filter_html = render_date_filter(start, end, extra_params=extra_params)

    if df.empty:
        return render_page(
            "Compare - WP6 Red", filter_html + "<h1>No data found</h1>",
            show_back_link=True, back_url="/compare",
        )

    if has_right:
        fig = make_dual_axis_chart(df, left_label, right_label)
    else:
        fig = make_line_chart(df, title=left_label)
    chart_html = fig.to_html(full_html=False, include_plotlyjs="cdn")

    stats_html = f"<small>{len(df):,} data points</small>"

    return render_page(
        "Compare - WP6 Red",
        filter_html + stats_html + chart_html,
        show_logo=False, show_footer=False, show_back_link=True, back_url="/compare",
    )


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    metadata_path = EXPORT_DIR / "metadata.json"
    if not metadata_path.exists():
        return None
    try:
        return json.loads(metadata_path.read_text())
    except Exception:
        return None


@app.get("/download/{table}")
async def download_csv(table: str, user: str = Depends(verify_auth)) -> FileResponse:
    """Download pre-generated CSV for a sensor table."""
    csv_path = EXPORT_DIR / f"{table}.csv"
    if not csv_path.exists():
        raise HTTPException(status_code=404, detail=f"No export available for {table}")

    return FileResponse(
        path=csv_path,
        media_type="text/csv",
        filename=f"{table}.csv",
    )


# =============================================================================
# DLI (Daily Light Integral) Endpoints
# =============================================================================

# Weather client (shared across requests)
weather_client: OpenMeteoClient | None = None


def get_weather_client() -> OpenMeteoClient:
    """Get or create weather client."""
    global weather_client
    if weather_client is None:
        weather_client = OpenMeteoClient()
    return weather_client


@app.get("/dli", response_class=HTMLResponse)
async def dli_home(user: str = Depends(verify_auth)) -> str:
    """DLI dashboard overview page."""
    if not db:
        return render_page("DLI - WP6 Red", "<h1>Database not connected</h1>", show_back_link=True)

    # Get model status for the card
    model = get_model()
    user_is_admin = is_admin(user)

    # Build model card based on status and permissions
    if model.is_trained() and model.stats:
        trained_date = model.stats.training_date.strftime("%Y-%m-%d")
        r2 = model.stats.r2_score
        model_status = f"""
            <p class="success">Trained: {trained_date}</p>
            <small>R² = {r2:.3f}</small>
        """
    else:
        model_status = "<small>Not trained</small>"

    if user_is_admin:
        model_card = f"""
            <article>
                <h3>Prediction Model</h3>
                <p>Train ML model to predict indoor PAR from weather data.</p>
                {model_status}
                <a href="/dli/model" class="btn">Manage Model</a>
            </article>
        """
    else:
        model_card = f"""
            <article class="card-disabled">
                <h3>Prediction Model</h3>
                <p>ML model to predict indoor PAR from weather data.</p>
                {model_status}
                <span class="btn-disabled">Admin only</span>
            </article>
        """

    extra_css = """
        .grid { display: grid; gap: 20px;
                grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); }
        .grid article { margin-bottom: 0; }
        .grid article h3 { margin-top: 0; }
        .card-disabled { opacity: 0.6; }
        .btn { display: inline-block; padding: 8px 16px; background: var(--pico-primary-background);
               color: var(--pico-primary-inverse); text-decoration: none; border-radius: 4px;
               margin-right: 8px; }
        .btn:hover { opacity: 0.85; text-decoration: none; }
        .btn-disabled { display: inline-block; padding: 8px 16px; background: #ccc;
                       color: #666; border-radius: 4px; font-size: 0.9em; }
    """

    content = f"""
        <h1>DLI Dashboard</h1>
        <p>Daily Light Integral analysis for PAR sensors.</p>

        <div class="grid">
            <article>
                <h3>Historical DLI</h3>
                <p>Compare natural light vs total light (with lamps) over time.</p>
                <a href="/dli/chart" class="btn">View Chart</a>
            </article>

            <article>
                <h3>Schedule Analysis</h3>
                <p>Predict plant light based on schedule and weather data.</p>
                <a href="/dli/schedule" class="btn">Analyze Schedule</a>
            </article>

            {model_card}
        </div>
    """

    return render_page("DLI Dashboard - WP6 Red", content, extra_css=extra_css, show_back_link=True)


@app.get("/dli/chart", response_class=HTMLResponse)
async def dli_chart(
    user: str = Depends(verify_auth),
    start: Annotated[date | None, Query(description="Start date")] = None,
    end: Annotated[date | None, Query(description="End date")] = None,
) -> str:
    """DLI chart comparing natural light vs total light over time."""
    if not db:
        return render_page("DLI Chart - WP6 Red", "<h1>Database not connected</h1>",
                          show_back_link=True, back_url="/dli")

    start, end, start_dt, end_dt = resolve_date_range(start, end)

    try:
        par_df = await db.get_par_readings(
            device_ids=[NATURAL_LIGHT_SENSOR, TOTAL_LIGHT_SENSOR], start=start_dt, end=end_dt
        )
    except Exception as e:
        return render_page("DLI Chart - WP6 Red", f"<h1>Error: {e}</h1>",
                          show_back_link=True, back_url="/dli")

    filter_html = render_date_filter(start, end)

    if par_df.empty:
        return render_page(
            "DLI Chart - WP6 Red",
            filter_html + "<h1>No PAR data found</h1>",
            show_back_link=True, back_url="/dli",
        )

    # Calculate DLI per device per day
    dli_df = calculate_daily_dli(par_df)

    if dli_df.empty:
        return render_page(
            "DLI Chart - WP6 Red",
            filter_html + "<h1>Insufficient data for DLI calculation</h1>",
            show_back_link=True, back_url="/dli",
        )

    # Rename devices to friendly labels
    device_labels = {
        NATURAL_LIGHT_SENSOR: "Natural Light",
        TOTAL_LIGHT_SENSOR: "Total Light",
    }
    dli_df["source"] = dli_df["device"].map(device_labels).fillna(dli_df["device"])

    # Pivot data for cleaner charts
    natural_data = dli_df[dli_df["device"] == NATURAL_LIGHT_SENSOR][
        ["date", "dli", "photoperiod_hours"]
    ].rename(columns={"dli": "natural_dli", "photoperiod_hours": "natural_hours"})
    total_data = dli_df[dli_df["device"] == TOTAL_LIGHT_SENSOR][
        ["date", "dli", "photoperiod_hours"]
    ].rename(columns={"dli": "total_dli", "photoperiod_hours": "total_hours"})

    chart_df = natural_data.merge(total_data, on="date", how="outer").sort_values("date")

    # Create DLI line chart with area fill
    import plotly.graph_objects as go

    fig_dli = go.Figure()
    fig_dli.add_trace(go.Scatter(
        x=chart_df["date"], y=chart_df["total_dli"],
        name="Total Light", mode="lines+markers",
        line={"color": "#2ecc71", "width": 2},
        marker={"size": 6},
        fill="tozeroy", fillcolor="rgba(46, 204, 113, 0.2)",
    ))
    fig_dli.add_trace(go.Scatter(
        x=chart_df["date"], y=chart_df["natural_dli"],
        name="Natural Light", mode="lines+markers",
        line={"color": "#3498db", "width": 2},
        marker={"size": 6},
        fill="tozeroy", fillcolor="rgba(52, 152, 219, 0.2)",
    ))

    # Add trendline for Total DLI
    total_valid = chart_df.dropna(subset=["total_dli"])
    if len(total_valid) >= 2:
        trendline_y, slope_per_day = calculate_dli_trendline(
            total_valid["date"].tolist(),
            total_valid["total_dli"].values,
        )
        trend_label = f"Trend ({slope_per_day:+.2f}/day)"
        fig_dli.add_trace(go.Scatter(
            x=total_valid["date"], y=trendline_y,
            name=trend_label, mode="lines",
            line={"color": "#e74c3c", "width": 2, "dash": "dash"},
        ))

    fig_dli.update_layout(
        title="Daily Light Integral (DLI)",
        yaxis_title="DLI (mol/m²/day)",
        xaxis_title="",
        height=400,
        hovermode="x unified",
        legend={"orientation": "h", "yanchor": "bottom", "y": 1.02, "xanchor": "right", "x": 1},
        margin={"t": 60, "b": 40},
    )
    chart_dli_html = fig_dli.to_html(full_html=False, include_plotlyjs="cdn")

    # Create photoperiod chart
    fig_hours = go.Figure()
    fig_hours.add_trace(go.Bar(
        x=chart_df["date"], y=chart_df["total_hours"],
        name="Total Hours", marker_color="#2ecc71",
    ))
    fig_hours.update_layout(
        title="Photoperiod (hours of light)",
        yaxis_title="Hours",
        xaxis_title="",
        height=300,
        hovermode="x unified",
        margin={"t": 60, "b": 40},
    )
    chart_hours_html = fig_hours.to_html(full_html=False, include_plotlyjs=False)

    # Summary stats
    days_count = len(chart_df)
    natural_avg = chart_df["natural_dli"].mean() if "natural_dli" in chart_df else 0
    total_avg = chart_df["total_dli"].mean() if "total_dli" in chart_df else 0
    hours_avg = chart_df["total_hours"].mean() if "total_hours" in chart_df else 0

    extra_css = """
        .chart-section { margin-bottom: 30px; }
        td, th { text-align: center; }
    """

    stats_html = f"""
        <div class="stats-grid cols-4">
            <article>
                <div class="stat-value">{total_avg:.1f}</div>
                <small>Avg Total DLI</small>
            </article>
            <article>
                <div class="stat-value">{natural_avg:.1f}</div>
                <small>Avg Natural DLI</small>
            </article>
            <article>
                <div class="stat-value">{hours_avg:.1f}h</div>
                <small>Avg Photoperiod</small>
            </article>
            <article>
                <div class="stat-value">{days_count}</div>
                <small>Days</small>
            </article>
        </div>
    """

    # Build data table
    table_df = chart_df.sort_values("date", ascending=False)
    table_rows = []
    for _, row in table_df.iterrows():
        natural_dli_val = f"{row['natural_dli']:.1f}" if pd.notna(row.get("natural_dli")) else "-"
        total_dli_val = f"{row['total_dli']:.1f}" if pd.notna(row.get("total_dli")) else "-"
        total_hrs = f"{row['total_hours']:.1f}" if pd.notna(row.get("total_hours")) else "-"

        # Calculate lamp contribution
        lamp_dli = calculate_lamp_contribution(
            row.get("total_dli") if pd.notna(row.get("total_dli")) else None,
            row.get("natural_dli") if pd.notna(row.get("natural_dli")) else None,
        )
        lamp_str = f"{lamp_dli:.1f}" if lamp_dli is not None else "-"

        table_rows.append(f"""
            <tr>
                <td>{row['date']}</td>
                <td>{natural_dli_val}</td>
                <td>{total_dli_val}</td>
                <td>{lamp_str}</td>
                <td>{total_hrs}</td>
            </tr>
        """)

    table_html = f"""
        <details>
            <summary>View Data Table</summary>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Natural DLI</th>
                        <th>Total DLI</th>
                        <th>Lamp DLI</th>
                        <th>Photoperiod</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(table_rows)}
                </tbody>
            </table>
        </details>
    """

    content = f"""
        {filter_html}
        {stats_html}
        <div class="chart-section">{chart_dli_html}</div>
        <div class="chart-section">{chart_hours_html}</div>
        {table_html}
    """

    return render_page(
        "DLI Chart - WP6 Red",
        content,
        extra_css=extra_css,
        show_logo=False, show_footer=False, show_back_link=True, back_url="/dli",
    )


@app.get("/dli/schedule", response_class=HTMLResponse)
async def dli_schedule(
    user: str = Depends(verify_auth),
    start_date: Annotated[date | None, Query(description="Start date")] = None,
    end_date: Annotated[date | None, Query(description="End date")] = None,
) -> str:
    """Analyze light schedule with predictions based on inferred lamp schedule."""
    if not db:
        return render_page("Schedule Analysis - WP6 Red", "<h1>Database not connected</h1>",
                          show_back_link=True, back_url="/dli")

    # Default to today
    today = date.today()
    if start_date is None:
        start_date = today
    if end_date is None:
        end_date = start_date

    # Ensure valid range
    if end_date < start_date:
        end_date = start_date

    sensor = os.getenv("WP6_RED_DLI_SCHEDULE_SENSOR", "s2100-02-par")
    yesterday = today - timedelta(days=1)

    # Get yesterday's data for inferring lamp schedule
    yesterday_start = datetime(yesterday.year, yesterday.month, yesterday.day, tzinfo=UTC)
    yesterday_end = yesterday_start + timedelta(days=1) - timedelta(seconds=1)

    try:
        yesterday_par_df = await db.get_par_readings(
            device_ids=[sensor], start=yesterday_start, end=yesterday_end
        )
    except Exception as e:
        return render_page("Schedule Analysis - WP6 Red", f"<h1>Error: {e}</h1>",
                          show_back_link=True, back_url="/dli")

    # Calculate yesterday's DLI
    yesterday_dli = 0.0
    if not yesterday_par_df.empty:
        yesterday_daily = calculate_daily_dli(yesterday_par_df)
        if not yesterday_daily.empty:
            yesterday_dli = yesterday_daily["dli"].iloc[0]

    # Get weather client and model
    client = get_weather_client()
    model = get_model()

    # Infer lamp schedule from yesterday (hourly: actual - predicted natural)
    inferred_lamp_hourly: dict[int, float] = {}  # hour -> lamp PAR
    yesterday_natural_dli = 0.0
    if not yesterday_par_df.empty and model.is_trained():
        try:
            yesterday_weather = await client.get_historical(yesterday, yesterday)
            if yesterday_weather:
                forecast = yesterday_weather[0]
                yesterday_natural_dli = model.predict_dli(forecast.total_radiation)

                # Calculate hourly averages from actual data
                yesterday_hourly = calculate_hourly_par(yesterday_par_df)

                # Infer lamp schedule using extracted function
                inferred_lamp_hourly = infer_lamp_schedule_hourly(
                    yesterday_hourly,
                    yesterday_natural_dli,
                    forecast.hourly,
                    forecast.total_radiation,
                )
        except Exception:
            pass  # Fall back to no lamp inference

    # Get data for selected date range
    range_start = datetime(start_date.year, start_date.month, start_date.day, tzinfo=UTC)
    range_end = datetime(end_date.year, end_date.month, end_date.day, tzinfo=UTC)
    range_end = range_end + timedelta(days=1) - timedelta(seconds=1)

    try:
        par_df = await db.get_par_readings(device_ids=[sensor], start=range_start, end=range_end)
    except Exception as e:
        return render_page("Schedule Analysis - WP6 Red", f"<h1>Error: {e}</h1>",
                          show_back_link=True, back_url="/dli")

    # Prepare actual data for chart (raw readings)
    actual_df = None
    if not par_df.empty:
        actual_df = par_df.rename(columns={"time": "datetime", "value": "par"})

    # Get weather for date range (for predictions)
    predicted_df = None
    natural_df = None

    if model.is_trained():
        try:
            # Get weather data for date range - combine historical and forecast as needed
            forecasts = []

            # Fetch historical weather for past dates
            if start_date < today:
                hist_end = min(end_date, today - timedelta(days=1))
                historical = await client.get_historical(start_date, hist_end)
                forecasts.extend(historical)

            # Fetch forecast for today and future dates
            if end_date >= today:
                all_forecasts = await client.get_forecast(days=14)
                for f in all_forecasts:
                    if f.date >= today and start_date <= f.date <= end_date:
                        forecasts.append(f)

            predicted_records = []
            natural_records = []

            for forecast in forecasts:
                day_natural_dli = model.predict_dli(forecast.total_radiation)

                for h in forecast.hourly:
                    # Calculate natural PAR for this hour using extracted function
                    natural_par = estimate_hourly_natural_par(
                        day_natural_dli, h.solar_radiation, forecast.total_radiation
                    )

                    natural_records.append({"datetime": h.datetime, "par": natural_par})

                    # Calculate predicted PAR = inferred lamp + natural
                    lamp_par = inferred_lamp_hourly.get(h.datetime.hour, 0.0)
                    predicted_par = natural_par + lamp_par
                    predicted_records.append({"datetime": h.datetime, "par": predicted_par})

            if predicted_records:
                predicted_df = pd.DataFrame(predicted_records)
                predicted_df["datetime"] = pd.to_datetime(predicted_df["datetime"], utc=True)

            if natural_records:
                natural_df = pd.DataFrame(natural_records)
                natural_df["datetime"] = pd.to_datetime(natural_df["datetime"], utc=True)

        except Exception:
            pass  # Predictions unavailable

    # Calculate daily DLI values for annotations and cards
    daily_dli: dict[date, dict] = {}  # date -> {actual, predicted, natural}
    tomorrow = today + timedelta(days=1)

    # Add yesterday's actual and natural DLI (already calculated above)
    if yesterday_dli > 0:
        daily_dli[yesterday] = {"actual": yesterday_dli}
    if yesterday_natural_dli > 0:
        daily_dli.setdefault(yesterday, {})["natural"] = yesterday_natural_dli

    # Actual DLI per day from selected range
    if not par_df.empty:
        actual_daily = calculate_daily_dli(par_df)
        for _, row in actual_daily.iterrows():
            d = row["date"].date() if hasattr(row["date"], "date") else row["date"]
            daily_dli.setdefault(d, {})["actual"] = row["dli"]

    # Predicted/natural DLI per day (from forecasts)
    if predicted_df is not None and not predicted_df.empty:
        predicted_df["date"] = predicted_df["datetime"].dt.date
        for d, grp in predicted_df.groupby("date"):
            dli = grp["par"].sum() * SECONDS_PER_HOUR / UMOL_TO_MOL
            daily_dli.setdefault(d, {})["predicted"] = dli

    if natural_df is not None and not natural_df.empty:
        natural_df["date"] = natural_df["datetime"].dt.date
        for d, grp in natural_df.groupby("date"):
            dli = grp["par"].sum() * SECONDS_PER_HOUR / UMOL_TO_MOL
            daily_dli.setdefault(d, {})["natural"] = dli

    # Ensure today and tomorrow have predictions for cards (if not already in range)
    if model.is_trained():
        for card_date in [today, tomorrow]:
            if card_date not in daily_dli or "predicted" not in daily_dli.get(card_date, {}):
                try:
                    forecasts = await client.get_forecast(days=7)
                    for f in forecasts:
                        if f.date == card_date:
                            nat_dli = model.predict_dli(f.total_radiation)
                            # Calculate predicted = natural + inferred lamp
                            pred_dli = nat_dli
                            for h in f.hourly:
                                lamp = inferred_lamp_hourly.get(h.datetime.hour, 0.0)
                                pred_dli += lamp * SECONDS_PER_HOUR / UMOL_TO_MOL
                            daily_dli.setdefault(card_date, {})["predicted"] = pred_dli
                            daily_dli.setdefault(card_date, {})["natural"] = nat_dli
                            break
                except Exception:
                    pass

    # For today: combine actual (observed so far) + predicted remainder
    current_hour = datetime.now(UTC).hour
    today_vals_tmp = daily_dli.get(today, {})
    has_today_data = "actual" in today_vals_tmp and "predicted" in today_vals_tmp
    if has_today_data and predicted_df is not None and not predicted_df.empty:
        remainder_dli = estimate_remaining_dli(predicted_df, today, current_hour)
        daily_dli[today]["estimated"] = today_vals_tmp["actual"] + remainder_dli

    # Build chart
    title = f"Light Schedule - {start_date}" if start_date == end_date else \
            f"Light Schedule - {start_date} to {end_date}"
    fig = make_schedule_chart(
        actual_df=actual_df,
        predicted_df=predicted_df,
        natural_df=natural_df,
        title=title,
    )

    # Add daily DLI annotations at noon of each day (at bottom to avoid legend)
    for d, values in sorted(daily_dli.items()):
        noon = datetime(d.year, d.month, d.day, 12, tzinfo=UTC)
        parts = []
        if "actual" in values:
            parts.append(f"A:{values['actual']:.1f}")
        if "predicted" in values:
            parts.append(f"P:{values['predicted']:.1f}")
        if "natural" in values:
            parts.append(f"N:{values['natural']:.1f}")
        if parts:
            fig.add_annotation(
                x=noon, y=0.02, yref="paper", yanchor="bottom",
                text="<br>".join(parts),
                showarrow=False, font={"size": 10}, bgcolor="rgba(255,255,255,0.8)",
                bordercolor="#ccc", borderwidth=1, borderpad=4,
            )

    chart_html = fig.to_html(full_html=False, include_plotlyjs="cdn")

    # Get DLI values for yesterday, today, tomorrow cards
    yesterday_vals = daily_dli.get(yesterday, {})
    today_vals = daily_dli.get(today, {})
    tomorrow_vals = daily_dli.get(tomorrow, {})

    unit = '<span class="unit">mol/m²</span>'

    def format_card_value(vals: dict, use_estimated: bool = False) -> str:
        if use_estimated and "estimated" in vals:
            return f"{vals['estimated']:.1f}~ {unit}"
        if "actual" in vals:
            return f"{vals['actual']:.1f} {unit}"
        if "predicted" in vals:
            return f"{vals['predicted']:.1f}* {unit}"
        return "-"

    def format_card_sublabel(vals: dict) -> str:
        if "natural" in vals:
            return f"(natural: {vals['natural']:.1f})"
        return ""

    extra_css = """
        .schedule-controls { padding: 0.75rem 1rem; }
        .schedule-controls form { display: flex; gap: 1rem; align-items: end;
                                  flex-wrap: wrap; margin-bottom: 0; }
        .schedule-controls label { margin-bottom: 0; }
        .stat-value .unit { font-size: 0.5em; font-weight: normal; color: #999; }
    """

    controls_html = f"""
        <article class="schedule-controls">
            <form method="get">
                <label>Start
                    <input type="date" name="start_date" value="{start_date}"
                           onchange="this.form.submit()">
                </label>
                <label>End
                    <input type="date" name="end_date" value="{end_date}"
                           onchange="this.form.submit()">
                </label>
            </form>
        </article>
    """

    stats_html = f"""
        <div class="stats-grid">
            <article>
                <div class="stat-value">{format_card_value(yesterday_vals)}</div>
                <small>Yesterday</small><br>
                <small>{format_card_sublabel(yesterday_vals)}</small>
            </article>
            <article>
                <div class="stat-value">{format_card_value(today_vals, use_estimated=True)}</div>
                <small>Today</small><br>
                <small>{format_card_sublabel(today_vals)}</small>
            </article>
            <article>
                <div class="stat-value">{format_card_value(tomorrow_vals)}</div>
                <small>Tomorrow</small><br>
                <small>{format_card_sublabel(tomorrow_vals)}</small>
            </article>
        </div>
        <small>* predicted ~ estimated</small>
    """

    content = f"""
        <h1>Daily Light Integral (DLI) Analysis</h1>
        {controls_html}
        {stats_html}
        {chart_html}
        <small>
            A/P/N = Actual / Predicted / Natural DLI values per day.<br/>
            Natural light predictions are based on the current ML model.<br/>
            Total predicted is yesterday's inferred lamp schedule + natural light.
        </small>
    """

    return render_page(
        "Daily Light Integral (DLI) - WP6 Red",
        content,
        extra_css=extra_css,
        show_logo=False, show_footer=False, show_back_link=True, back_url="/dli",
    )


@app.get("/dli/model", response_class=HTMLResponse)
async def dli_model_status(user: str = Depends(verify_admin_auth)) -> str:
    """View model status and training options."""
    model = get_model()

    if model.is_trained() and model.stats:
        stats = model.stats
        s1 = stats.stage1
        s2 = stats.stage2

        # Show feature names if available
        s1_features = getattr(s1, "feature_names", list(s1.coefficients.keys()))
        s2_features = getattr(s2, "feature_names", list(s2.coefficients.keys()))

        s1_coef_rows = "".join(
            f"<tr><td>{name}</td><td>{s1.coefficients.get(name, 0):+.4f}</td></tr>"
            for name in s1_features
        )
        s2_coef_rows = "".join(
            f"<tr><td>{name}</td><td>{s2.coefficients.get(name, 0):+.4f}</td></tr>"
            for name in s2_features
        )

        # Model version info
        model_version = getattr(stats, "model_version", 4)
        model_type = "Ridge regression" if model_version >= 5 else "Linear regression"

        status_html = f"""
            <article>
                <h3 class="success">Two-Stage Model Trained (Daily)</h3>
                <p>OpenMeteo weather → s1000 daily lux → indoor PAR ({model_type})</p>

                <div class="stats-grid cols-5">
                    <article>
                        <div class="stat-value">{stats.r2_score:.3f}</div>
                        <small>Combined R²</small>
                    </article>
                    <article>
                        <div class="stat-value">{s1.r2_score:.3f}</div>
                        <small>Stage 1 R²</small>
                    </article>
                    <article>
                        <div class="stat-value">{s2.r2_score:.3f}</div>
                        <small>Stage 2 R²</small>
                    </article>
                    <article>
                        <div class="stat-value">{stats.n_samples:,}</div>
                        <small>Days</small>
                    </article>
                    <article>
                        <div class="stat-value">\
{getattr(stats, 'attenuation_factor', 1.0):.3f}</div>
                        <small>Attenuation</small>
                    </article>
                </div>

                <h4>Stage 1: Weather API → Local Lux (Daily)</h4>
                <p>Calibrates OpenMeteo weather to s1000 daily lux sum
                   (R²={s1.r2_score:.3f}, RMSE={s1.rmse:.0f} lux/day)</p>
                <small>Features: {', '.join(s1_features)}</small>
                <table>
                    <tr><th>Feature</th><th>Coefficient</th></tr>
                    <tr><td>Intercept</td><td>{s1.intercept:+.4f}</td></tr>
                    {s1_coef_rows}
                </table>

                <h4>Stage 2: Outdoor Lux → Indoor PAR (Daily)</h4>
                <p>Greenhouse transmission model for daily totals
                   (R²={s2.r2_score:.3f}, RMSE={s2.rmse:.1f} μmol/m²/day)</p>
                <small>Features: {', '.join(s2_features)}</small>
                <table>
                    <tr><th>Feature</th><th>Coefficient</th></tr>
                    <tr><td>Intercept</td><td>{s2.intercept:+.4f}</td></tr>
                    {s2_coef_rows}
                </table>

                <small>
                    Outdoor sensor: <strong>{stats.outdoor_sensor}</strong><br>
                    Indoor sensor: <strong>{stats.indoor_sensor}</strong><br>
                    Attenuation: <strong>{getattr(stats, 'attenuation_factor', 1.0):.4f}</strong>
                    ({getattr(stats, 'attenuation_samples', 0)} days)<br>
                    Trained: {stats.training_date.strftime('%Y-%m-%d %H:%M')} UTC<br>
                    Data range: {stats.date_range[0]} to {stats.date_range[1]}<br>
                    Model version: v{model_version}
                </small>
            </article>
        """
    else:
        status_html = """
            <article>
                <h3 class="warning">No Model Trained</h3>
                <p>The two-stage PAR prediction model has not been trained yet.</p>
                <p>Training requires:</p>
                <ul>
                    <li><strong>Stage 1</strong>: OpenMeteo weather data + s1000 lux readings</li>
                    <li><strong>Stage 2</strong>: s1000 lux + s2100-01-par indoor readings</li>
                </ul>
            </article>
        """

    train_form = """
        <article>
            <h3>Train Model</h3>
            <p>Trains a two-stage model:</p>
            <ol>
                <li><strong>Stage 1</strong>: OpenMeteo → s1000 lux (weather API calibration)</li>
                <li><strong>Stage 2</strong>: s1000 lux → indoor PAR (greenhouse transmission)</li>
            </ol>
            <form method="post" action="/dli/model/train">
                <button type="submit">Train Model</button>
            </form>
            <small>
                Uses all data from s1000 and s2100-01-par since 2025-10-24.
            </small>
        </article>
    """

    content = f"""
        <h1>Light Prediction Model</h1>
        <p>Two-stage ML model: OpenMeteo forecast → local calibration → indoor PAR prediction.</p>
        {status_html}
        {train_form}
        <p>
            <a href="/dli/model/diagnostic">View training diagnostic</a> -
            investigate data alignment and correlation issues.
        </p>
    """

    return render_page(
        "Light Model - WP6 Red",
        content,
        show_back_link=True, back_url="/dli",
    )


@app.post("/dli/model/train", response_class=HTMLResponse)
async def dli_model_train(user: str = Depends(verify_admin_auth)) -> str:
    """Train the two-stage light prediction model."""
    if not db:
        return render_page(
            "Train Model - WP6 Red",
            "<h1>Database not connected</h1>",
            show_back_link=True, back_url="/dli/model",
        )

    # Use all data since DEFAULT_TRAINING_START (devices up and running)
    start_dt = datetime(
        DEFAULT_TRAINING_START.year,
        DEFAULT_TRAINING_START.month,
        DEFAULT_TRAINING_START.day,
        tzinfo=UTC,
    )
    end_dt = datetime.now(UTC)

    # Fetch PAR data from both sensors for lamp correction
    try:
        above_lamp_df = await db.get_par_readings(
            device_ids=[NATURAL_LIGHT_SENSOR], start=start_dt, end=end_dt
        )
        plant_level_df = await db.get_par_readings(
            device_ids=[TOTAL_LIGHT_SENSOR], start=start_dt, end=end_dt
        )
    except Exception as e:
        return render_page(
            "Train Model - WP6 Red",
            f"<h1>Database Error (indoor PAR)</h1><p>{e}</p>",
            show_back_link=True, back_url="/dli/model",
        )

    if above_lamp_df.empty:
        return render_page(
            "Train Model - WP6 Red",
            "<h1>No Indoor PAR Data</h1>"
            "<p>No s2100-01-par readings found for the selected date range.</p>",
            show_back_link=True, back_url="/dli/model",
        )

    # Stage 2 trains on s2100-01-par (above lamps, clean r=0.911 with s1000)
    indoor_df = above_lamp_df
    indoor_sensor_label = "s2100-01-par"

    # Fetch outdoor weather station data (s1000 lux)
    try:
        outdoor_df = await db.get_weather_station_readings(start=start_dt, end=end_dt)
    except Exception as e:
        return render_page(
            "Train Model - WP6 Red",
            f"<h1>Database Error (s1000)</h1><p>{e}</p>",
            show_back_link=True, back_url="/dli/model",
        )

    if outdoor_df.empty:
        return render_page(
            "Train Model - WP6 Red",
            "<h1>No Weather Station Data</h1>"
            "<p>No s1000 lux readings found for the selected date range.</p>",
            show_back_link=True, back_url="/dli/model",
        )

    # Fetch OpenMeteo historical weather data (direct + diffuse radiation for better model)
    client = get_weather_client()
    try:
        weather_df = await client.get_historical_dataframe_multi(
            start_dt.date(), end_dt.date(),
            radiation_var="direct_radiation",
            include_diffuse=True,
        )
    except Exception as e:
        return render_page(
            "Train Model - WP6 Red",
            f"<h1>Weather API Error</h1><p>{e}</p>",
            show_back_link=True, back_url="/dli/model",
        )

    if weather_df.empty:
        return render_page(
            "Train Model - WP6 Red",
            "<h1>No OpenMeteo Data</h1>"
            "<p>Could not fetch weather data for the date range.</p>",
            show_back_link=True, back_url="/dli/model",
        )

    # Train two-stage model
    model = get_model()
    try:
        stats = model.train(
            weather_df=weather_df,
            outdoor_df=outdoor_df,
            indoor_df=indoor_df,
            indoor_sensor=indoor_sensor_label,
            plant_level_df=plant_level_df if not plant_level_df.empty else None,
            above_lamp_df=above_lamp_df,
        )
        model.save()
    except ValueError as e:
        return render_page(
            "Train Model - WP6 Red",
            f"<h1>Training Failed</h1><p>{e}</p>",
            show_back_link=True, back_url="/dli/model",
        )
    except Exception as e:
        return render_page(
            "Train Model - WP6 Red",
            f"<h1>Training Error</h1><p>{e}</p>",
            show_back_link=True, back_url="/dli/model",
        )

    extra_css = """
        .success-card { border: 2px solid green; border-radius: 8px; padding: 20px;
                       background: #f0fff0; }
    """

    content = f"""
        <div class="success-card">
            <h1>Two-Stage Model Trained (Daily)</h1>
            <div class="stats-grid cols-5">
                <article>
                    <div class="stat-value">{stats.r2_score:.3f}</div>
                    <small>Combined R²</small>
                </article>
                <article>
                    <div class="stat-value">{stats.stage1.r2_score:.3f}</div>
                    <small>Stage 1 R²</small>
                </article>
                <article>
                    <div class="stat-value">{stats.stage2.r2_score:.3f}</div>
                    <small>Stage 2 R²</small>
                </article>
                <article>
                    <div class="stat-value">{stats.n_samples:,}</div>
                    <small>Days</small>
                </article>
                <article>
                    <div class="stat-value">{stats.attenuation_factor:.3f}</div>
                    <small>Attenuation</small>
                </article>
            </div>
            <p><strong>Stage 1</strong>: OpenMeteo daily direct_radiation → s1000 daily lux</p>
            <p><strong>Stage 2</strong>: s1000 daily lux → s2100-01-par (above-lamp)
               → ×{stats.attenuation_factor:.3f} → plant-level estimate</p>
            <p>
                Model saved and will be used for PAR predictions.
                <a href="/dli/model">View full model details</a>
            </p>
        </div>
    """

    return render_page(
        "Model Trained - WP6 Red",
        content,
        extra_css=extra_css,
        show_back_link=True, back_url="/dli/model",
    )


@app.get("/dli/model/diagnostic", response_class=HTMLResponse)
async def dli_model_diagnostic(
    user: str = Depends(verify_admin_auth),
) -> str:
    """Diagnostic view to investigate model training data."""
    if not db:
        return render_page(
            "Model Diagnostic - WP6 Red",
            "<h1>Database not connected</h1>",
            show_back_link=True, back_url="/dli/model",
        )

    # Use same date range as training
    start_dt = datetime(
        DEFAULT_TRAINING_START.year,
        DEFAULT_TRAINING_START.month,
        DEFAULT_TRAINING_START.day,
        tzinfo=UTC,
    )
    end_dt = datetime.now(UTC)

    # Fetch all data sources
    try:
        indoor_df = await db.get_par_readings(
            device_ids=[NATURAL_LIGHT_SENSOR], start=start_dt, end=end_dt
        )
        plant_level_df = await db.get_par_readings(
            device_ids=[TOTAL_LIGHT_SENSOR], start=start_dt, end=end_dt
        )
        outdoor_df = await db.get_weather_station_readings(start=start_dt, end=end_dt)

        # Fetch weather with direct_radiation + diffuse (for improved model)
        client = get_weather_client()
        weather_df = await client.get_historical_dataframe_multi(
            start_dt.date(), end_dt.date(),
            radiation_var="direct_radiation",
            include_diffuse=True,
        )
    except Exception as e:
        return render_page(
            "Model Diagnostic - WP6 Red",
            f"<h1>Error fetching data</h1><p>{e}</p>",
            show_back_link=True, back_url="/dli/model",
        )

    # Data counts
    indoor_count = len(indoor_df)
    plant_level_count = len(plant_level_df)
    outdoor_count = len(outdoor_df)
    weather_count = len(weather_df)

    # Check date ranges
    def date_range_str(df, time_col="time"):
        if df.empty:
            return "No data"
        col = time_col if time_col in df.columns else "datetime"
        dates = pd.to_datetime(df[col], utc=True)
        return f"{dates.min().date()} to {dates.max().date()}"

    indoor_range = date_range_str(indoor_df)
    plant_level_range = date_range_str(plant_level_df)
    outdoor_range = date_range_str(outdoor_df)
    weather_range = date_range_str(weather_df, "datetime")

    # Align data for scatter plot (Stage 1: weather vs outdoor)
    stage1_merged = align_weather_outdoor_hourly(
        weather_df, outdoor_df, min_lux=10.0, min_radiation=0.0
    )
    if "solar_radiation" in stage1_merged.columns:
        stage1_merged = stage1_merged[stage1_merged["solar_radiation"] > 0]

    # Create scatter plot
    import plotly.express as px

    if not stage1_merged.empty:
        fig = px.scatter(
            stage1_merged,
            x="solar_radiation",
            y="lux",
            title="Stage 1: OpenMeteo Solar Radiation vs s1000 Lux",
            labels={"solar_radiation": "OpenMeteo Solar Radiation (W/m²)", "lux": "s1000 Lux"},
        )
        fig.update_layout(height=500)
        scatter_html = fig.to_html(full_html=False, include_plotlyjs="cdn")
    else:
        scatter_html = "<p>No aligned data for scatter plot</p>"

    # Calculate correlation comparison using extracted function
    corr_stats = calculate_correlation_comparison(stage1_merged, "solar_radiation", "lux")
    corr = corr_stats["hourly_corr"]
    daily_corr = corr_stats["daily_corr"]
    daily_samples = corr_stats["daily_samples"]

    # Analyze reporting frequency using extracted function
    freq_stats = analyze_reporting_frequency(outdoor_df, "time")
    median_interval = freq_stats["median_interval_minutes"]
    readings_per_hour = freq_stats["readings_per_hour"]
    days_with_few = freq_stats["days_with_few_readings"]
    total_days = freq_stats["total_days"]

    # =========================================================================
    # Stage 2 Diagnostics: s1000 → s2100-01-par (Above-Lamp PAR)
    # =========================================================================
    stage2_sections = []

    if not indoor_df.empty and not plant_level_df.empty:
        # 1. Lamp Profile Summary
        lamp_profile = derive_daily_lamp_profile(indoor_df, plant_level_df)
        if not lamp_profile.empty:
            days_with_lamp = int(lamp_profile["lamp_power_par"].notna().sum())
            total_profile_days = len(lamp_profile)
            lamp_powers = lamp_profile["lamp_power_par"].dropna()
            median_lamp_power = float(lamp_powers.median()) if len(lamp_powers) > 0 else 0.0

            # Average lamp schedule hours (lamp_end - lamp_start + 1 for days with lamps)
            lamp_days = lamp_profile.dropna(subset=["lamp_start", "lamp_end"])
            if not lamp_days.empty:
                lamp_hours = lamp_days.apply(
                    lambda r: (r["lamp_end"] - r["lamp_start"] + 1)
                    if r["lamp_start"] <= r["lamp_end"]
                    else (24 - r["lamp_start"] + r["lamp_end"] + 1),
                    axis=1,
                )
                avg_lamp_hours = float(lamp_hours.mean())
            else:
                avg_lamp_hours = 0.0

            stage2_sections.append(f"""
                <div class="diag-section">
                    <h3>Lamp Profile Summary</h3>
                    <p>Derived from {NATURAL_LIGHT_SENSOR} (above lamp) and
                       {TOTAL_LIGHT_SENSOR} (plant level)</p>
                    <div class="stats-grid">
                        <article>
                            <div class="stat-value">{days_with_lamp}/{total_profile_days}</div>
                            <small>Days with lamp detected</small>
                        </article>
                        <article>
                            <div class="stat-value">{median_lamp_power:.0f}</div>
                            <small>Median lamp PAR (μmol/m²/s)</small>
                        </article>
                        <article>
                            <div class="stat-value">{avg_lamp_hours:.1f}h</div>
                            <small>Avg lamp schedule</small>
                        </article>
                    </div>
                </div>
            """)
        else:
            stage2_sections.append("""
                <div class="diag-section">
                    <h3>Lamp Profile Summary</h3>
                    <small>No overlapping days between sensors
                       for lamp profile derivation.</small>
                </div>
            """)

        # 2. Stage 2 Scatter: s1000 → s2100-01-par (current training target)
        if not outdoor_df.empty:
            import plotly.graph_objects as go

            # s1000 → s2100-01-par (above lamp, no lamp contamination)
            above_lamp_stage = align_outdoor_to_indoor_daily(outdoor_df, indoor_df)

            if not above_lamp_stage.empty:
                fig_roof = go.Figure()
                fig_roof.add_trace(go.Scatter(
                    x=above_lamp_stage["lux_sum"],
                    y=above_lamp_stage["par_sum"],
                    mode="markers",
                    name="s1000 → s2100-01-par",
                    marker={"color": "#3498db", "size": 6, "opacity": 0.6},
                ))
                fig_roof.update_layout(
                    title="Stage 2: s1000 Daily Lux → s2100-01-par (above lamp)",
                    xaxis_title="s1000 Daily Lux Sum",
                    yaxis_title="s2100-01-par Daily PAR Sum",
                    height=400,
                )
                roof_html = fig_roof.to_html(full_html=False, include_plotlyjs=False)
            else:
                roof_html = "<p>No aligned data for s1000 → s2100-01-par</p>"

            stage2_sections.append(f"""
                <div class="diag-section">
                    <h3>Scatter: s1000 → s2100-01-par (Daily)</h3>
                    {roof_html}
                </div>
            """)

            # 3. Stage 2 Correlation + model attenuation factor
            corr_parts = []

            if not above_lamp_stage.empty and len(above_lamp_stage) >= 2:
                r_roof = float(above_lamp_stage["lux_sum"].corr(above_lamp_stage["par_sum"]))
                r_roof = r_roof if pd.notna(r_roof) else 0.0
                n_roof = len(above_lamp_stage)
                corr_parts.append(f"""
                    <article>
                        <div class="stat-value">{r_roof:.3f}</div>
                        <small>Stage 2: s1000 → s2100-01 (r) - {n_roof} days</small>
                    </article>
                """)

            # s2100-01-par → s2100-02-par (attenuation correlation)
            above = indoor_df.copy()
            plant = plant_level_df.copy()
            above["time"] = pd.to_datetime(above["time"], utc=True)
            plant["time"] = pd.to_datetime(plant["time"], utc=True)
            above["date"] = above["time"].dt.date
            plant["date"] = plant["time"].dt.date
            above_daily = above.groupby("date").agg({"value": "sum"}).reset_index()
            above_daily.columns = ["date", "above_par_sum"]
            plant_daily = plant.groupby("date").agg({"value": "sum"}).reset_index()
            plant_daily.columns = ["date", "plant_par_sum"]
            internal_stage = above_daily.merge(plant_daily, on="date", how="inner")
            internal_stage = internal_stage[
                (internal_stage["above_par_sum"] > 0) & (internal_stage["plant_par_sum"] > 0)
            ]

            if not internal_stage.empty and len(internal_stage) >= 2:
                r_int = float(
                    internal_stage["above_par_sum"].corr(internal_stage["plant_par_sum"])
                )
                r_int = r_int if pd.notna(r_int) else 0.0
                n_int = len(internal_stage)
                corr_parts.append(f"""
                    <article>
                        <div class="stat-value">{r_int:.3f}</div>
                        <small>Attenuation: s2100-01 → s2100-02 (r) - {n_int} days</small>
                    </article>
                """)

            # Show stored model attenuation factor if available
            model = get_model()
            if model.stats and model.stats.attenuation_factor != 1.0:
                corr_parts.append(f"""
                    <article>
                        <div class="stat-value">{model.stats.attenuation_factor:.3f}</div>
                        <small>Model attenuation factor</small>
                    </article>
                """)

            if corr_parts:
                stage2_sections.append(f"""
                    <div class="diag-section">
                        <h3>Stage 2 Correlation</h3>
                        <div class="stats-grid">
                            {''.join(corr_parts)}
                        </div>
                    </div>
                """)

            # 4. Attenuation Validation: s2100-01-par → s2100-02-par scatter
            if not internal_stage.empty:
                fig_int = go.Figure()
                fig_int.add_trace(go.Scatter(
                    x=internal_stage["above_par_sum"],
                    y=internal_stage["plant_par_sum"],
                    mode="markers",
                    name="s2100-01-par → s2100-02-par",
                    marker={"color": "#9b59b6", "size": 6, "opacity": 0.6},
                ))
                fig_int.update_layout(
                    title="Attenuation Validation: s2100-01-par → s2100-02-par",
                    xaxis_title="s2100-01-par Daily PAR Sum (above lamp)",
                    yaxis_title="s2100-02-par Daily PAR Sum (plant level)",
                    height=400,
                )
                int_html = fig_int.to_html(full_html=False, include_plotlyjs=False)
            else:
                int_html = "<p>No aligned data for s2100-01-par → s2100-02-par</p>"

            stage2_sections.append(f"""
                <div class="diag-section">
                    <h3>Scatter: s2100-01-par → s2100-02-par (Attenuation Validation)</h3>
                    {int_html}
                </div>
            """)

            # 5. Attenuation Ratio: corrected s2100-02-par / s2100-01-par
            #    Must use lamp-corrected data, otherwise ratio is
            #    (natural+lamp)/natural which is meaningless.
            if not lamp_profile.empty and lamp_profile["lamp_power_par"].notna().any():
                corrected_df = subtract_lamp_from_sensor(plant_level_df, lamp_profile)
                corr_plant = corrected_df.copy()
                corr_plant["time"] = pd.to_datetime(corr_plant["time"], utc=True)
                corr_plant["date"] = corr_plant["time"].dt.date
                corr_plant_daily = (
                    corr_plant.groupby("date").agg({"value": "sum"}).reset_index()
                )
                corr_plant_daily.columns = ["date", "plant_par_sum"]
                ratio_df = above_daily.merge(corr_plant_daily, on="date", how="inner")
                ratio_df = ratio_df[
                    (ratio_df["above_par_sum"] > 0) & (ratio_df["plant_par_sum"] > 0)
                ]
            else:
                ratio_df = pd.DataFrame()

            if not ratio_df.empty and len(ratio_df) >= 2:
                ratio_df["ratio"] = (
                    ratio_df["plant_par_sum"] / ratio_df["above_par_sum"]
                )
                ratio_df["date"] = pd.to_datetime(ratio_df["date"])
                ratio_df = ratio_df.sort_values("date")

                median_ratio = float(ratio_df["ratio"].median())
                min_ratio = float(ratio_df["ratio"].min())
                max_ratio = float(ratio_df["ratio"].max())

                # Rolling median to show seasonal trend
                window = min(14, len(ratio_df))
                ratio_df["rolling_median"] = (
                    ratio_df["ratio"].rolling(window, center=True, min_periods=3).median()
                )

                # Deviation from rolling median to find local outliers
                ratio_df["deviation"] = ratio_df["ratio"] - ratio_df["rolling_median"]
                dev_std = float(ratio_df["deviation"].std())
                outlier_mask = ratio_df["deviation"] < -2 * dev_std
                n_outliers = int(outlier_mask.sum())
                clean_n = len(ratio_df) - n_outliers

                # Time series with rolling median
                fig_ratio = go.Figure()
                clean_df = ratio_df[~outlier_mask]
                outlier_df = ratio_df[outlier_mask]

                fig_ratio.add_trace(go.Scatter(
                    x=clean_df["date"], y=clean_df["ratio"],
                    mode="markers", name="Daily ratio",
                    marker={"color": "#3498db", "size": 6, "opacity": 0.6},
                ))
                if not outlier_df.empty:
                    fig_ratio.add_trace(go.Scatter(
                        x=outlier_df["date"], y=outlier_df["ratio"],
                        mode="markers", name=f"Occlusion ({n_outliers}d)",
                        marker={"color": "#e74c3c", "size": 8, "symbol": "x"},
                    ))
                fig_ratio.add_trace(go.Scatter(
                    x=ratio_df["date"], y=ratio_df["rolling_median"],
                    mode="lines", name=f"Rolling median ({window}d)",
                    line={"color": "#2ecc71", "width": 2},
                ))
                fig_ratio.add_hline(
                    y=median_ratio, line_dash="dot", line_color="#999",
                    annotation_text=f"Global median: {median_ratio:.3f}",
                    annotation_position="top left",
                )
                fig_ratio.update_layout(
                    title="Daily Attenuation Ratio (lamp-corrected s2100-02 / s2100-01)",
                    xaxis_title="",
                    yaxis_title="Ratio (corrected plant / above-lamp)",
                    height=400,
                    legend={"orientation": "h", "yanchor": "bottom", "y": 1.02,
                            "xanchor": "right", "x": 1},
                )
                ratio_chart_html = fig_ratio.to_html(
                    full_html=False, include_plotlyjs=False
                )

                # Trend assessment: range of rolling median
                rolling_clean = ratio_df["rolling_median"].dropna()
                if len(rolling_clean) >= 2:
                    trend_min = float(rolling_clean.min())
                    trend_max = float(rolling_clean.max())
                    trend_range = trend_max - trend_min
                    trend_pct = trend_range / median_ratio * 100
                    trend_label = f"{trend_min:.3f} – {trend_max:.3f} ({trend_pct:.0f}% swing)"
                else:
                    trend_label = "-"

                # Show model's stored factor for comparison
                model_factor_html = ""
                if model.stats and model.stats.attenuation_factor != 1.0:
                    model_factor_html = f"""
                        <article>
                            <div class="stat-value">{model.stats.attenuation_factor:.3f}</div>
                            <small>Model factor (stored)</small>
                        </article>
                    """

                stage2_sections.append(f"""
                    <div class="diag-section">
                        <h3>Attenuation: s2100-01 → Plant-Level</h3>
                        <small>Ratio of lamp-corrected plant-level to
                           above-lamp daily PAR (natural light only).
                           Rolling median shows seasonal trend.
                           Red crosses = days &gt;2&sigma; below local trend
                           (likely plant occlusion).</small>
                        <div class="stats-grid cols-auto">
                            <article>
                                <div class="stat-value">{median_ratio:.3f}</div>
                                <small>Live median</small>
                            </article>
                            {model_factor_html}
                            <article>
                                <div class="stat-value">{min_ratio:.3f} – {max_ratio:.3f}</div>
                                <small>Range (all days)</small>
                            </article>
                            <article>
                                <div class="stat-value">{trend_label}</div>
                                <small>Rolling median range</small>
                            </article>
                            <article>
                                <div class="stat-value warning">{n_outliers}</div>
                                <small>Occlusion days ({clean_n} clean)</small>
                            </article>
                        </div>
                        {ratio_chart_html}
                    </div>
                """)

    else:
        stage2_sections.append("""
            <div class="diag-section">
                <h3>Stage 2 Data</h3>
                <small>Missing sensor data for Stage 2 diagnostics.
                   Need both s2100-01-par and s2100-02-par readings.</small>
            </div>
        """)

    stage2_html = "\n".join(stage2_sections)

    extra_css = """
        .diag-section { margin: 20px 0; padding: 15px; background: #f9f9f9;
                       border-radius: 8px; }
        .diag-section h3 { margin-top: 0; }
    """

    warn_class = "warning" if days_with_few > 10 else ""
    daily_class = "success" if daily_corr > corr else ""

    content = f"""
        <h1>Model Training Diagnostic</h1>
        <small>Using <strong>direct_radiation</strong> from OpenMeteo</small>

        <div class="diag-section">
            <h3>Raw Data Counts</h3>
            <div class="stats-grid cols-4">
                <article>
                    <div class="stat-value">{indoor_count:,}</div>
                    <small>Above-lamp PAR ({NATURAL_LIGHT_SENSOR})</small>
                </article>
                <article>
                    <div class="stat-value">{plant_level_count:,}</div>
                    <small>Plant-level PAR ({TOTAL_LIGHT_SENSOR})</small>
                </article>
                <article>
                    <div class="stat-value">{outdoor_count:,}</div>
                    <small>s1000 readings</small>
                </article>
                <article>
                    <div class="stat-value">{weather_count:,}</div>
                    <small>OpenMeteo hours</small>
                </article>
            </div>
            <small>
                Above-lamp: {indoor_range}<br>
                Plant-level: {plant_level_range}<br>
                Outdoor: {outdoor_range}<br>
                Weather: {weather_range}
            </small>
        </div>

        <div class="diag-section">
            <h3>s1000 Reporting</h3>
            <p>Median interval: <strong>{median_interval:.1f} min</strong>
               (~{readings_per_hour:.0f} readings/hour)</p>
        </div>

        <div class="diag-section">
            <h3>Stage 1: OpenMeteo → s1000 Correlation</h3>
            <div class="stats-grid">
                <article>
                    <div class="stat-value">{corr:.3f}</div>
                    <small>Hourly (r) - {len(stage1_merged)} samples</small>
                </article>
                <article>
                    <div class="stat-value {daily_class}">{daily_corr:.3f}</div>
                    <small>Daily totals (r) - {daily_samples} days</small>
                </article>
                <article>
                    <div class="stat-value {warn_class}">{days_with_few}/{total_days}</div>
                    <small>Days with &lt;20 readings</small>
                </article>
            </div>
        </div>

        <div class="diag-section">
            <h3>Stage 1: Scatter (OpenMeteo vs s1000)</h3>
            {scatter_html}
        </div>

        <hr>
        <h2>Stage 2 &amp; Attenuation</h2>
        {stage2_html}
    """

    return render_page(
        "Model Diagnostic - WP6 Red",
        content,
        extra_css=extra_css,
        show_back_link=True, back_url="/dli/model",
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
