"""Red dashboard dependencies: config, auth, globals, helpers."""

from pathlib import Path

from dotenv import load_dotenv

from wp6_data.config import RedSettings
from wp6_data.red.db import MySQLConnection
from wp6_data.red.dli import OpenMeteoClient
from wp6_data.shared.export import get_export_metadata as _get_export_metadata
from wp6_data.shared.metadata import MetadataRegistry

load_dotenv()

settings = RedSettings()
metadata = MetadataRegistry(Path(__file__).parent / "metadata.yaml")

# MySQL connection settings
DB_HOST = settings.db_host
DB_PORT = settings.db_port
DB_NAME = settings.db_name
DB_USER = settings.db_user
DB_PASSWORD = settings.db_password

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(settings.export_dir)

# Database connection (managed via lifespan in dashboard.py)
db: MySQLConnection | None = None

# Weather client (shared across requests)
weather_client: OpenMeteoClient | None = None


def get_weather_client() -> OpenMeteoClient:
    """Get or create weather client."""
    global weather_client
    if weather_client is None:
        weather_client = OpenMeteoClient()
    return weather_client


def _export_info_html(export_meta: dict | None) -> str:
    """Generate HTML snippet showing export metadata."""
    if not export_meta:
        return "<small>CSV exports not yet available.</small>"
    return ""


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    return _get_export_metadata(EXPORT_DIR)
