"""Red dashboard dependencies: config, auth, globals, helpers."""

import json
import os
from pathlib import Path

from authlib.integrations.starlette_client import OAuth
from dotenv import load_dotenv
from fastapi import Depends, HTTPException
from starlette.requests import Request

from wp6_data.red.db import MySQLConnection
from wp6_data.red.dli import OpenMeteoClient

load_dotenv()

# Serve static files (logo, etc.) from project root
# __file__ is src/wp6_data/red/deps.py, so .parent x4 gets to wp6-data/
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent

# MySQL connection settings
DB_HOST = os.getenv("WP6_RED_DB_HOST", "localhost")
DB_PORT = int(os.getenv("WP6_RED_DB_PORT", "3306"))
DB_NAME = os.getenv("WP6_RED_DB_NAME", "spohf2")
DB_USER = os.getenv("WP6_RED_DB_USER", "root")
DB_PASSWORD = os.getenv("WP6_RED_DB_PASSWORD", "")

# OIDC settings (Keycloak)
OIDC_ISSUER = os.getenv("WP6_RED_OIDC_ISSUER", "https://auth.fontysvenlo.dev/realms/spohf")
OIDC_CLIENT_ID = os.getenv("WP6_RED_OIDC_CLIENT_ID", "wp6-red-dashboard")
OIDC_CLIENT_SECRET = os.getenv("WP6_RED_OIDC_CLIENT_SECRET", "")
SESSION_SECRET = os.getenv("WP6_RED_SESSION_SECRET", "")
ADMIN_GROUP = os.getenv("WP6_RED_ADMIN_GROUP", "/wp6-admins")

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(os.getenv("WP6_RED_EXPORT_DIR", "/data/exports"))

# Database connection (managed via lifespan in dashboard.py)
db: MySQLConnection | None = None

# Weather client (shared across requests)
weather_client: OpenMeteoClient | None = None

# OAuth / OIDC client
oauth = OAuth()
oauth.register(
    name="keycloak",
    client_id=OIDC_CLIENT_ID,
    client_secret=OIDC_CLIENT_SECRET,
    server_metadata_url=f"{OIDC_ISSUER}/.well-known/openid-configuration",
    client_kwargs={"scope": "openid profile email"},
)


class NotAuthenticated(Exception):
    """Raised when a request has no valid session — triggers redirect to login."""


def verify_auth(request: Request) -> str:
    """Check session for authenticated user; raise NotAuthenticated if missing."""
    user = request.session.get("user")
    if not user:
        raise NotAuthenticated
    return user


def is_admin(request: Request) -> bool:
    """Check if the logged-in user belongs to the admin group."""
    groups = request.session.get("groups", [])
    return ADMIN_GROUP in groups


def verify_admin_auth(request: Request, user: str = Depends(verify_auth)) -> str:
    """Verify user has admin access (for model training etc.)."""
    if not is_admin(request):
        raise HTTPException(status_code=403, detail="Admin access required")
    return user


def get_weather_client() -> OpenMeteoClient:
    """Get or create weather client."""
    global weather_client
    if weather_client is None:
        weather_client = OpenMeteoClient()
    return weather_client


def _export_info_html(export_meta: dict | None) -> str:
    """Generate HTML snippet showing export metadata."""
    if not export_meta:
        return "<small>CSV exports not yet available.</small>"
    return ""


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    metadata_path = EXPORT_DIR / "metadata.json"
    if not metadata_path.exists():
        return None
    try:
        return json.loads(metadata_path.read_text())
    except Exception:
        return None
