"""Red dashboard dependencies: config, auth, globals, helpers."""

import json
import os
import secrets
from pathlib import Path
from typing import Annotated

from dotenv import load_dotenv
from fastapi import Depends, HTTPException
from fastapi.security import HTTPBasic, HTTPBasicCredentials

from wp6_data.red.db import MySQLConnection
from wp6_data.red.dli import OpenMeteoClient

load_dotenv()

# Serve static files (logo, etc.) from project root
# __file__ is src/wp6_data/red/deps.py, so .parent x4 gets to wp6-data/
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent

# MySQL connection settings
DB_HOST = os.getenv("WP6_RED_DB_HOST", "localhost")
DB_PORT = int(os.getenv("WP6_RED_DB_PORT", "3306"))
DB_NAME = os.getenv("WP6_RED_DB_NAME", "spohf2")
DB_USER = os.getenv("WP6_RED_DB_USER", "root")
DB_PASSWORD = os.getenv("WP6_RED_DB_PASSWORD", "")

# Auth users: "user1:pass1,user2:pass2" (required, no default)
AUTH_USERS_STR = os.getenv("WP6_RED_AUTH_USERS", "")

# Admin users: comma-separated list of usernames with admin access
ADMIN_USERS_STR = os.getenv("WP6_RED_ADMIN_USERS", "admin")
ADMIN_USERS = {u.strip() for u in ADMIN_USERS_STR.split(",") if u.strip()}


def parse_users(users_str: str) -> dict[str, str]:
    """Parse users from comma-separated string."""
    if not users_str:
        return {}
    users = {}
    for pair in users_str.split(","):
        if ":" in pair:
            username, password = pair.split(":", 1)
            users[username.strip()] = password.strip()
    return users


AUTH_USERS = parse_users(AUTH_USERS_STR)

# CSV export directory (pre-generated by nightly job)
EXPORT_DIR = Path(os.getenv("WP6_RED_EXPORT_DIR", "/data/exports"))

# Database connection (managed via lifespan in dashboard.py)
db: MySQLConnection | None = None

# Weather client (shared across requests)
weather_client: OpenMeteoClient | None = None

security = HTTPBasic()


def verify_auth(credentials: Annotated[HTTPBasicCredentials, Depends(security)]) -> str:
    """Verify Basic Auth credentials."""
    if not AUTH_USERS:
        raise HTTPException(
            status_code=500,
            detail="No users configured. Set WP6_RED_AUTH_USERS env var.",
        )

    if credentials.username not in AUTH_USERS:
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Basic"},
        )

    expected_password = AUTH_USERS[credentials.username]
    if not secrets.compare_digest(credentials.password.encode(), expected_password.encode()):
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Basic"},
        )

    return credentials.username


def is_admin(user: str) -> bool:
    """Check if user has admin access."""
    return user in ADMIN_USERS


def verify_admin_auth(user: str = Depends(verify_auth)) -> str:
    """Verify user has admin access (for model training etc.)."""
    if not is_admin(user):
        raise HTTPException(
            status_code=403,
            detail="Admin access required",
        )
    return user


def get_weather_client() -> OpenMeteoClient:
    """Get or create weather client."""
    global weather_client
    if weather_client is None:
        weather_client = OpenMeteoClient()
    return weather_client


def _export_info_html(export_meta: dict | None) -> str:
    """Generate HTML snippet showing export metadata."""
    if not export_meta:
        return "<small>CSV exports not yet available.</small>"
    return ""


def get_export_metadata() -> dict | None:
    """Get metadata about available CSV exports."""
    metadata_path = EXPORT_DIR / "metadata.json"
    if not metadata_path.exists():
        return None
    try:
        return json.loads(metadata_path.read_text())
    except Exception:
        return None
